### ISSUE TITLE
Replace splash screen

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#1]
**data/images/gimp-splash.svg** needs to replaced with a new alternative.

We can either keep the filename for now to avoid code changes, or it can be renamed "wilber-splash.svg" if the related code is changed.

We should aim to reduce the size of the SVG to less than 50MB to comply with Github's rules on file sizes.

**Comment by Member1221** [comment]
PR https://github.com/glimpse-editor/Glimpse/pull/27 should address this

**Comment by TrechNex** [comment]
Fixed in #137
