### ISSUE TITLE
More means of donating

### ISSUE THREAD

**Issue by barrel0luck** [glimpse-editor/Glimpse#101]
Hi! I just read about Glimpse on omg!ubuntu! and I love the idea and want to support it, esp, since the GIMP devs seem to be hating it. 
Can you please arrange for more means for donating? I usually donate using one-off donations (but regularly). 
It could be useful for people who are nervous about giving off debit/credit card details to various intermediaries. You might even get more contributions that way!
May this project see great success!!!

**Comment by Member1221** [comment]
Hey @TrechNex you are the one managing that.

**Comment by TrechNex** [comment]
I'm open to suggestions on this! eg. Setting up an account on Liberapay should be straightforward. 

I will need to have a think about how to provide a PayPal email address as we don't have mail forwarding addresses for the getglimpse.app domain. It may be better on that side of things to provide a list of addresses for individual contributors like upstream does.

Other suggestions for platforms are welcome! (I am wary of accepting cryptocurrency as it's not unheard of for fraudsters to use a stolen credit card to send an outlandish donation to a project then immediately ask for a refund to cover their tracks)

**Comment by jmooring** [comment]
If a few bucks will help I'd be happy to donate as soon as the mechanism is in place.

**Comment by TrechNex** [comment]
OpenCollective was suggested earlier in chat

https://opencollective.com/how-it-works

**Comment by TrechNex** [comment]
To confirm, we created an Open Collective page here: https://opencollective.com/glimpse
