### ISSUE TITLE
Glimpse is offensive

### ISSUE THREAD

**Issue by Conzar** [glimpse-editor/Glimpse#103]
> The initial aim is to provide a downstream fork of the GNU Image Manipulation Program that has a less problematic name so there are no barriers to using the software in businesses and educational institutions.

Glimpse is offensive to some people somewhere on the internet and therefore is not suitable for businesses and educational institutions.  Please change the name.

**Comment by TrechNex** [comment]
I refer you to this FAQ: https://getglimpse.app/about/#what-if-i-find-the-word-glimpse-offensive
