### ISSUE TITLE
Collapse tools in tool bar

### ISSUE THREAD

**Issue by Member1221** [glimpse-editor/Glimpse#107]
Right now the tools in the tool bar are an absolute mess. I suggest getting inspiration from Photoshop and collapsing tools under "main" tools of their type.

I personally want to work on this for 0.1.1, but it could be pushed back based on how hard it is to add in the current code base.

![billede](https://user-images.githubusercontent.com/7032834/63793324-c6db7e80-c8ff-11e9-8141-d2059b3f0a3d.png)
(image taken from photoshopessentials.com)

How it looks currently (on my setup)
![billede](https://user-images.githubusercontent.com/7032834/63793484-128e2800-c900-11e9-81b3-9b7546e7d205.png)

Such a change would be offered to upstream if they'd want it.

**Comment by chaomodus** [comment]
Big ol +1 from me, this would make the toolbox *way* less annoyingn

**Comment by TrechNex** [comment]
This has already been implemented by upstream in 2.10.18. Assigning to 0.2.0 milestone as that will be based on 2.10.20.

**Comment by TrechNex** [comment]
We could potentially achieve that kind of behaviour by tweaking the default UI configuration. If you can re-jig the user interface and send me your config folder then that would help me puzzle out the changes we need.

cc @Member1221 @chaomodus

**Comment by TrechNex** [comment]
Closing as we already get folding of this kind in 2.10.18. If we want to change default behaviour, we should raise a new issue.
