### ISSUE TITLE
Name is offensive

### ISSUE THREAD

**Issue by mrpendulum** [glimpse-editor/Glimpse#110]
It reads like something that someone would try to do non-consensually to someone else, and is highly offensive. Please change it.

**Comment by BrainBlasted** [comment]
Troll issue. Seeya o/

**Comment by TrechNex** [comment]
In case this is a thing that comes back up, claiming that *a word to do with seeing* is offensive on the grounds peeping toms exist is clearly a bad faith argument by people who wrongly think they're hoisting this project with its own petard. I agree with the decision @BrainBlasted made here.
