### ISSUE TITLE
Create a decent useable interface

### ISSUE THREAD

**Issue by sketchbuch** [glimpse-editor/Glimpse#115]
You've got rid of the crap name, now please get rid of that crap interface - The current one looks like it was designed by herman munster circa 1986.

The number of people who don't use GIMP because of the name pales into insignificance next to those who don't use it because of the way it looks and the way information is presented to them and the fact that the diabolical joke of an interface seems to have been designed to hinder use of the program.

**Comment by BrainBlasted** [comment]
We're working on it - though I'd prefer if you didn't refer to other projects' work as crap, even if you dislike it :)

**Comment by AliKhomami** [comment]
Hi, Where can we post our mockups and UI concepts?

**Comment by Member1221** [comment]
@AliKhomami please contact us via our matrix channel to get access to the matrix channel for mockups.
