### ISSUE TITLE
Windows Packaging with WiX

### ISSUE THREAD

**Issue by Member1221** [glimpse-editor/Glimpse#119]
## How
Windows will be packaged with [WiX](https://wixtoolset.org/) which can be automated.
Once we're at the windows packaging stage of development, we need to write an XML definition file for our installer.

## What we need to do

- [ ] Get a WiX install script up and running
- [ ] Customize our installer's look
  - [ ] Potentially add options for selecting plugins/features to include with installation
- [ ] Automate installer creation via build system (jenkins)

**Comment by RayoGundead** [comment]
[Chocolatey](https://chocolatey.org/) and [Scoop](https://scoop.sh/) would be nice.

**Comment by Member1221** [comment]
> [Chocolatey](https://chocolatey.org/) and [Scoop](https://scoop.sh/) would be nice.

As I said in the previous issue; we have limited capacity to make packaging for a lot of things. WiX will be the official packaging, but if a high-quality community package for chocolatey or scoop appears we could feature it on the website.

**Comment by TrechNex** [comment]
On the automation side of things we can hopefully get it to work with TravisCI.

Would also suggest investigating how upstream currently packages for Windows. I can already see scripts for creating zip files, etc so there could also be some legacy cruft for us to remove.

**Comment by TrechNex** [comment]
Linking to #58 as there is some duplication happening here.

**Comment by TrechNex** [comment]
Pushed this out as a 0.x candidate because there's nothing stopping us from writing our own MSI installer after the initial release of 0.1. I don't think it makes sense to delay the release until that new work is done.

I am adapting the existing installer to begin with. This would be an exe file that installs the correct build for 32-bit or 64-bit systems automatically.

**Comment by TrechNex** [comment]
32-bit MSI installer for beta testing is available here: https://build.glimpse-editor.org/beta/win32/

**Comment by TrechNex** [comment]
Current progress on this ticket can be tracked in this repo: https://github.com/TrechNex/glimpse-windows-installer

I will be creating a repo specifically set up to be reusable, with branches for each major release.

**Comment by TrechNex** [comment]
I think customizing the installers look and automating with Jenkins should be two new and separate Github Issues. There's no way those things can be achieved for 0.1, but there's an outside chance for 0.2.

**Comment by TrechNex** [comment]
Linking to Jenkins job issue #164

**Comment by TrechNex** [comment]
Moved to 0.2.0 Candidates as still work to do on 64-bit build and Jenkins job will not be done until after 0.1.0 is released.

**Comment by Boscop** [comment]
+1 for making it installable via scoop. 
It would also be great to have a portable zip download for Windows, instead of an installer.

**Comment by TrechNex** [comment]
For the purposes of the 0.2.0 milestone I'm going to count this as fixed. We should open a separate issue for automating the WiX packaging.

**Comment by bb010g** [comment]
Submitted a Scoop manifest patch to the extras bucket: lukesampson/scoop-extras#4842

With that merged, Glimpse v0.2.0 will be packaged on Windows by [winget](https://github.com/microsoft/winget-pkgs/tree/626a56487b46c8c0fddad05ea0565e9904a8b4ed/manifests/Glimpse), [Scoop](https://github.com/lukesampson/scoop-extras/blob/e4e10fc4d035547d1feaec84c85378b200f1899d/bucket/glimpse.json), and [Chocolatey](https://github.com/corbob/ChocoPackages/blob/9144ed3c8097d3f12a771214c889092d3c54203b/glimpse/glimpse.nuspec).

**Comment by TrechNex** [comment]
@bb010g did you see this issue: https://github.com/glimpse-editor/Glimpse/issues/65

It might be that my previous effort helps you progress. I am not able to get Scoop working on my own Windows machines, so wasn't able to test.
