### ISSUE TITLE
Will it be in AUR?

### ISSUE THREAD

**Issue by laichiaheng** [glimpse-editor/Glimpse#120]
It makes it easier to be intalled.

**Comment by ibrahimBeladi** [comment]
After reading #57, I guess it it unlikely at first. It might be done manually by a third-party entity. However, it might be supported at some point in the future.

**Comment by BrainBlasted** [comment]
I don't think we'll officially support the AUR, but nothing prevents those who want it from making a PKGBUILD :)

**Comment by Member1221** [comment]
A friend of mine plans to make an AUR package, so there probably will be shortly after we release.

**Comment by FabioLolix** [comment]
Hello, I have uploaded a pkgbuild to the AUR few hours ago

I had started working on it some days ago when seen Glimpse in the news, actually I don't use the program myself, pkgbuild co-maintainers are very welcome

https://aur.archlinux.org/packages/glimpse-editor-git/

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=glimpse-editor-git

**Comment by Member1221** [comment]
> Hello, I have uploaded a pkgbuild to the AUR few hours ago
> 
> I had started working on it some days ago when seen Glimpse in the news, actually I don't use the program myself, pkgbuild co-maintainers are very welcome
> 
> https://aur.archlinux.org/packages/glimpse-editor-git/
> 
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=glimpse-editor-git

There's a few instances where "gimp" could be replaced with glimpse, but otherwise the pkgbuild looks p good :)
