### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by Jnchi** [glimpse-editor/Glimpse#122]
There is already a project that goes by this name. It would be helpful to include a section in the README stating this.

https://github.com/Glimpse/Glimpse

**Comment by Member1221** [comment]
@Jnchi said project seems to not have been updated for a long time. We're not sure that naming conflict will be relevant at current time.

**Comment by TrechNex** [comment]
I double-checked this and ended up agreeing, as it took the count of Glimpse app name clashes to 6. Their URL is also extremely similar to our own.

See #92
