### ISSUE TITLE
Glimpse Software Foundation (feature request)

### ISSUE THREAD

**Issue by Al-Caveman** [glimpse-editor/Glimpse#123]
Hello.  First, thank you for your Glimpse editor fork.  I can finally use the editor in school without getting bullied by students and even teachers.

Since this movement is very successful, I suggest that you also spearhead the _Glimpse Software Foundation_, where all improperly named software gets forked to have the right name, as follows:

* GIMP -->  Glimpse image editor.
* Git --> Glimpse version control system.
* Qutebrowser --> Glimpse browser.

I have _fully_ forked `Qutebrowser` into `Glimpsebrowser`, including docs, file paths, module names, etc..  This is important to me, because the Q-word seems like an insult, so I couldn't use it at school either (but now I can after I forked it with a better name).  Here is the fork with the name fixing patch applied:  https://github.com/Al-Caveman/glimpsebrowser

I suggest to introduce a page where all corrected software is listed, so that people know about the better alternatives out there that they can use at school/work.  

Plus, so that they know that this movement is more serious, and naming is important, hence -hopefully- future software will have better names from the start.

**Comment by TrechNex** [comment]
I thought satire was dead on the Internet, but thank you for proving me wrong! :rofl:

**Comment by Al-Caveman** [comment]
I'm confused.  Why did you close this?  You called it even a joke?  All I did is exactly what "Glimpse editor" did, but to Q-word browser (another software with insult in its name).

**Comment by TrechNex** [comment]
I refer you to this FAQ answer: https://getglimpse.app/about/#are-you-just-forking-because-of-the-name

We are not going to start a software foundation with the sole purpose of forking every application whose name we consider distasteful. Contrary to what you may have heard, we have no intention of "policing" the free software world.
