### ISSUE TITLE
Glimpse name already taken by a software.

### ISSUE THREAD

**Issue by HumanG33k** [glimpse-editor/Glimpse#124]
Hello,

I just discover your work (with search in github) it looks like it’s a fork of gimp ?
I don’t really understand why ? and moreover why choose an already taken name ?

thx for clarification.

**Comment by DominicWatson** [comment]
For why, see: https://glimpse-editor.org/about/

For a discussion on the name, see https://github.com/glimpse-editor/Glimpse/issues/92 (where you can offer suggestions).

**Comment by HumanG33k** [comment]
Oo 

You are just insane, just for a name … Split all Free Software human resources for a name it’s just like don’t eat because of a vegetable color when you are starving. 

I think people are intelligent enough to understand the name … maybe not if there is a fork.

**Comment by TrechNex** [comment]
To confirm, there is no "split". The GNU Image Manipulation Project still has all the same developers they had before, and this project is made up of enthusiasts from outside that project .

It would have been better if we could have worked together, but if we have to fork we might as well avail ourselves of the opportunity to attract new contributors and ideas. 👍
