### ISSUE TITLE
Add contributing guide + new issue + new PR templates

### ISSUE THREAD

**Issue by DominicWatson** [glimpse-editor/Glimpse#128]
Full guide on Github: https://help.github.com/en/articles/about-issue-and-pull-request-templates.

## Example on npx

See https://github.com/npm/npx for example. Add:

* [CONTRIBUTING.md](https://github.com/npm/npx/blob/latest/CONTRIBUTING.md)
* [ISSUE_TEMPLATE](https://github.com/npm/npx/blob/latest/ISSUE_TEMPLATE)
* [PULL_REQUEST_TEMPLATE](https://github.com/npm/npx/blob/latest/PULL_REQUEST_TEMPLATE)

Files to the root of the project (links to examples).

**Comment by TrechNex** [comment]
Changes applied in #214 and #215 
(Don't read too much into your name being removed from AUTHORS files btw. You seem to have been duplicated a few times because of a mix of manual & automatic changes!)

**Comment by TrechNex** [comment]
I am still working on the `CONTRIBUTING.md` file, but should appear some time this evening.

**Comment by TrechNex** [comment]
Merged multiple PRs into one ready for review

**Comment by TrechNex** [comment]
Changes now merged into dev branch.
