### ISSUE TITLE
Red eye jumpscare built into the software should be removed

### ISSUE THREAD

**Issue by XenonFiber** [glimpse-editor/Glimpse#131]
https://gitlab.gnome.org/GNOME/gimp/merge_requests/124

**Comment by chaomodus** [comment]
I believe that @TrechNex has already patched out this easter egg and also the large wilber in an empty canvas in the dev branch.

**Comment by unascribed** [comment]
I just cloned the dev branch and the code is still very much here; unless it was patched out at a higher level or hasn't been committed yet, this is still around.

**Comment by unascribed** [comment]
Though, come to think of it I couldn't find the code that *draws* the red eyes, so I guess the timer is still here as well as the flag, just not the logic to do anything with the flag.

**Comment by chaomodus** [comment]
I think if you'd located the code for the timer, it'd be cool to submit a patch taking that out too!

**Comment by TrechNex** [comment]
You're both right. The code I removed related to the rendering of Wilber and their eyes on the main window. As I started this fork with zero knowledge of the original codebase it wouldn't surprise me if there are elements of that code I missed.

If you submit a patch, we'll merge it :)

**Comment by TrechNex** [comment]
Also a reminder that my code changes are in `dev-g210` branch. The `main` branch is basically the unaltered upstream 2.10.12 code that we haven't merged our changes into yet.

**Comment by TrechNex** [comment]
Update: As the patch looks fairly small I will take a look this evening (UK time). It's possible some of the changes in that revert PR have already been made or are unneeded.

**Comment by Member1221** [comment]
It should be removed as of #134, closing issue.
