### ISSUE TITLE
How can I try this?

### ISSUE THREAD

**Issue by saileshkush95** [glimpse-editor/Glimpse#133]
I didn't find any documentation that how to install this software for testing purpose.

**Comment by TrechNex** [comment]
We'll have to update the `README.md`!

Until we have the automated builds ready the best place to start is the `HACKING` file. I have provided some instructions that allow you to use [Vagrant](https://www.vagrantup.com/) to spin up a "development environment in a box". This creates a virtual machine with all the prerequisite packages, then you just have to SSH into it and run `glimpse-vagrant.sh`.

If you're using Linux as your host OS you should be able to run the pre-release Glimpse 0.1 from there. On Windows and Mac you will need to run a separate X Server like [Xming](https://sourceforge.net/projects/xming/).

**Comment by TrechNex** [comment]
Also tagging @chaomodus as we may want something about this on wiki as well

**Comment by chaomodus** [comment]
Hey good point!

**Comment by TrechNex** [comment]
To update on this, we now have a Wiki page with comprehensive instructions: https://wiki.glimpse-editor.org/index.php?title=Building_Glimpse

We still need to link to it from code level docs.

**Comment by TrechNex** [comment]
This should now be resolved. Code-level docs will be updated before release anyway.
