### ISSUE TITLE
Change config directory

### ISSUE THREAD

**Issue by Member1221** [glimpse-editor/Glimpse#138]
Currently we're loading configs from the same path as upstream, that will cause conflicts.
The upstream path is `~/.config/GIMP/2.10`
I suggest we go with `~/.config/glimpse`

**Comment by igalic** [comment]
do we need a versioning there too, or should we put that into the config files?

**Comment by TrechNex** [comment]
I would suggest stucking to what upstream do but just change the folder name.
Remember that this does not just affect Linux, but also Mac and Windows. For 0.1 we are also relying on upstream's help pages and docs.

Let's not make this more involved than it needs to be for now. (It also gives us the opportunity to change name of files like `.gimprc` at a later date)

**Comment by TrechNex** [comment]
Contrary to my earlier typo, the plan is for our config to move to `~/.config/Glimpse`.
As I am just using build flags to change the directory it's likely the version within that folder will be upstream (i.e. `2.10`) but I think that is fine for now.

**Comment by TrechNex** [comment]
Has now been changed to default to `~/.config/Glimpse`. Thank you @bochecha for pointing out where that needed fixing.

**Comment by TrechNex** [comment]
We should keep this issue open even after pull request is merged as I need to go through the code and make sure crash data & logs are stored in the right place.

I don't want to do this straight away as they're related to the Windows port, and it makes sense to make sure I set the right executable names, etc at the same time.

**Comment by TrechNex** [comment]
Linking to #119

**Comment by TrechNex** [comment]
Is fixed in #152
