### ISSUE TITLE
Add screenshots to the appdata

### ISSUE THREAD

**Issue by bochecha** [glimpse-editor/Glimpse#143]
Since #81 we have an Appdata file showing off Glimpse in software centers.

To really make it shine, we need good screenshots. At least 2 or 3 would be good. 

The [recommendations](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html#tag-dapp-screenshots) are the following:

> *   All screenshots should have a 16:9 aspect ratio, and should have a width that is no smaller than 620px (software center applications will be able to fill in the screenshots in the space they provide for that more easily then).
>     Ideally the window will be resized to a 16:9 aspect ratio, but screenshots can also be cropped if only a small area of the window needs to be shown.
> *   Screenshots should be in PNG or JPEG format. PNG is the preferred format; JPEG should only be used when screenshots include large photographs or other images where a lossy format like JPEG may compress better.
> *   Do not scale screenshots below their original size. 
> 
> You can find a lot more information on how to create good screenshots in the [quickstart guide on applications](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info). 

Those screenshots will need to be hosted somewhere accessible on HTTPS. Something under https://glimpse-editor.org/ would work fine.

Once those screenshots are available, we need to update the `desktop/org.glimpse_editor.Glimpse.appdata.xml.in.in` file to uncomment the `<screenshots>` section and point it to the right URLs.

**Comment by chaomodus** [comment]
![Screenshot from 2019-09-23 22-33-22](https://user-images.githubusercontent.com/151073/65483785-4eaa9f00-de52-11e9-9a8f-945ed7fc9f15.png)

Feel free to use this. The photo is mine.

**Comment by bochecha** [comment]
That's a great screenshot @chaomodus !

However, can you resize the window to have a 16:9 ratio as recommended in the spec?

**Comment by TrechNex** [comment]
Do you still need someone to do this, or are you able to do it with your own setup? I think it makes sense to ensure the screenshots are taken from the Flatpak :)

**Comment by bochecha** [comment]
> I think it makes sense to ensure the screenshots are taken from the Flatpak :)

That makes no difference whatsoever.

I'd really prefer someone else to do provide screenshots, because I don't use Glimpse (or the GNU IMP), and as such I have no idea what parts of the app are interesting to show off to potential users.

Something like @chaomodus's screenshot above is a great start. (although having it 16:9 would be better)

We'd need at least one or two more.

**Comment by TrechNex** [comment]
Okay. Looks like that will be my job tomorrow (Monday) morning 👍

**Comment by TrechNex** [comment]
Closing this as the screenshots are now publicly visible:
https://glimpse-editor.org/flatpak/0.1/dark-theme1.png
https://glimpse-editor.org/flatpak/0.1/light-theme2.png

**Comment by bochecha** [comment]
They aren't in the appdata yet though, not until #222 is merged. :man_shrugging:

**Comment by TrechNex** [comment]
This is true. But that PR is still open with a link to this issue for reference, and we also have another related issue still open. Closing this issue does not mean work stops :)

**Comment by BrainBlasted** [comment]
I think it's good to keep issues open until they're fully completed.On Nov 19, 2019 8:19 AM, Bobby Moss <notifications@github.com> wrote:This is true. But that PR is still open with a link to this issue for reference, and we also have another related issue still open. Closing this issue does not mean work stops :)

**Comment by TrechNex** [comment]
Okay. For the pedantically-inclined I will keep this issue open. I had closed it because the change had been applied in a PR and the images were live :stuck_out_tongue_closed_eyes:

**Comment by bochecha** [comment]
This was fixed by #222.
