### ISSUE TITLE
Fill the update_contact email address in the appdata

### ISSUE THREAD

**Issue by bochecha** [glimpse-editor/Glimpse#144]
Since #81 we have an Appdata file showing off Glimpse in software centers.

However, one thing it is missing is [the `<update_contact>` tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-update_contact):

>  The `<update_contact/>` tag is an optional tag which can be added to provide an email address distributors can use to contact the project about invalid or incomplete metadata or – in case the specification has changed – about old metadata. It can also be used to ask general questions in case of an update of the component described in the metadata file.
> 
> The `<update_contact/>` tag must *only be used by distributors*. It is not included in the distribution-provided AppStream XML file, and therefore not exposed to the end user via any kind of UI.
> 
> Upstream authors might decide to add an email address in cleartext, but spam protection using **\_AT\_** is also valid. The value of this tag is generally treated a case-insensitive way. 

So we need to have an email alias/mailing-list for this, and then we need to set the right value in the appdata file.

**Comment by TrechNex** [comment]
For now I'd suggest just using my public email contact [at] bobbymoss [dot] com. We can always change it in later releases.
