### ISSUE TITLE
Add release notes to the appdata

### ISSUE THREAD

**Issue by bochecha** [glimpse-editor/Glimpse#146]
Since #81 we have an Appdata file showing off Glimpse in software centers.

To really make it shine, we should add release notes to our releases, starting with 0.1.

This is achieved with [the `<releases>` tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases).

The appdata currently has it commented out.

When we're ready to release, we should uncomment it and write something down. See the comments in the appdata file for an example.

**Comment by TrechNex** [comment]
I will try to draft that some time this week. That way you should be able to copy and paste from a pull request on the website repository.

**Comment by bochecha** [comment]
Great, thanks.

What would be great is if you could publish the release notes to the website, but make it clear they are provisional, that Glimpse 0.1.0 is not released yet and still a work in progress.

This way we can have the appdata list the main thing, and point to that URL for more details.

**Comment by TrechNex** [comment]
Indeed, this was exactly what I was suggesting. While it's a PR it can be reviewed on Github by clicking the "markdown" previewer.

This seems like it would be less confusing than saying "These are our release note, but we've not released yet!" :)

**Comment by bochecha** [comment]
> Indeed, this was exactly what I was suggesting

Heh, I was suggesting the opposite. :stuck_out_tongue:

**Comment by TrechNex** [comment]
lol.

Basically I'm not okay with the idea of confusing people. So current plan is to add release notes at code level when I work on #128 (I'll be fixing the authors files and changelogs at the same time)

You should then be able to use that information for this change.

**Comment by TrechNex** [comment]
I think it makes sense to use what is in the `NEWS` file here. I will make sure this is up-to-date tomorrow.
