### ISSUE TITLE
I would like to help out with the visual branding process. 

### ISSUE THREAD

**Issue by jcklpe** [glimpse-editor/Glimpse#149]
I'm a design technologist. I have been using gimp since I was in middles school in 2004ish. I switched to Macromedia flash and then the Corel Painter 9/10 and then to Photoshop. I occasionally use krita too. 

I'd love to see a truly modern ui design and brand design alternative to PS in the open source feld. 

How an I help? 

I'm not some amateur futzing around with graphics. I work as  full time design technologist with 5 years experience at a top 100 marketing tech agency. You can check out my website here https://jackalope.tech

I've also got an ongoing open source design project I'm working on here https://github.com/jcklpe/Open-Source-Brandings

**Comment by Member1221** [comment]
You can start by visiting our matrix channel and talking to bob moss/trechnex.
Just say you want to be invited to the 2.x rewrite chat.

**Comment by TrechNex** [comment]
For reference, the necessary links are available here: https://glimpse-editor.org/contribute/

**Comment by TrechNex** [comment]
Also cc @BrainBlasted as he's taken on the redesign of our website (it's statically generated by Hugo and the source code is available here: https://github.com/glimpse-editor/getglimpse-web

Your insights could prove particularly valuable in that area. For UI redesign stuff you're better served by the Wiki link and connecting with us on Matrix as mentioned earlier.

Our branding assets are available here: https://github.com/glimpse-editor/branding
