### ISSUE TITLE
Can we change the name to PhotoExpress?

### ISSUE THREAD

**Issue by sammyplastic** [glimpse-editor/Glimpse#162]
I like how you forked this since the original name was offensive. But I find Glimpse to be offensive since when I have meltdowns, I have glimpses of past events in my head and this name reminds me of the bad times I have meltdowns.

I would like to suggest renaming this to PhotoExpress since you should be able to express yourself using images you create. Art is a beautiful and lets keep it that way!

**Comment by TrechNex** [comment]
Please make this suggestion in #92 where the OP has also launched a shared spreadsheet to canvas opinion for suggestions like these.
