### ISSUE TITLE
Create automated Jenkins job for Linux dev builds

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#163]
- [x] Create Jenkins job to build the Flatpak version of Glimpse 0.1
- [x] Create Flatpak repository for development builds
- [x] Update Jenkins job to publish Flatpak to development repository

**Comment by TrechNex** [comment]
@bochecha has been doing some fantastic work on this over the last couple of days 👏

**Comment by bochecha** [comment]
I think we're done with this: https://wiki.glimpse-editor.org/index.php?title=Testing_Glimpse#Flatpak

Let's close this issue?
