### ISSUE TITLE
Flatpak installation failed

### ISSUE THREAD

**Issue by ihabunek** [glimpse-editor/Glimpse#175]
Following instructions from: https://wiki.glimpse-editor.org/index.php?title=Testing_Glimpse

Adding the repo worked, but installation did not:

```
λ flatpak install glimpse_devel org.glimpse_editor.Glimpse                                                                      

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/ihabunek/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches…
error: Unable to load summary from remote glimpse_devel: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
```

I don't think the path warning is relevant.

On Debian 10 running sway wm. Flatpak installed from Debian's repos.

```
λ flatpak --version
Flatpak 1.2.4
```

**Comment by TrechNex** [comment]
My guess would be that you need to install the PPA version of Flatpak, as Debian will be running a much older version of it. I've assigned to @bochecha in case this is not expected behaviour.

**Comment by bochecha** [comment]
Thanks for the bug report @ihabunek.

What version of Flatpak do you have?

**Comment by ihabunek** [comment]
It's in the issue. :-)

-- Ivan

**Comment by bochecha** [comment]
Wiki updated.

Can you confirm this fixes the issue for you @ihabunek ?

**Comment by ihabunek** [comment]
New error: 
```
Looking for matches…

error: The application org.glimpse_editor.Glimpse/x86_64/devel requires the 
runtime org.gnome.Platform/x86_64/3.32 which was not found
```

Don't have time to play around with it now. Will try installing gnome platform later.

**Comment by bochecha** [comment]
> ```
> error: The application org.glimpse_editor.Glimpse/x86_64/devel requires the 
> runtime org.gnome.Platform/x86_64/3.32 which was not found
> ```

The wiki page does say you must enable Flathub first.

**Comment by ihabunek** [comment]
Hm, I followed the instructions for debian here: 
https://flatpak.org/setup/Debian/

I have flathub enabled:

```
λ flatpak remote-list
Name          Options
flathub       system
glimpse_devel user,no-gpg-verify
```

I even restarted the system, although I would not expect that to be required by a non-windows OS. :)

I still get the error, I'm not prompted to install the runtime.
```
λ flatpak install glimpse_devel org.glimpse_editor.Glimpse
Looking for matches…
error: The application org.glimpse_editor.Glimpse/x86_64/devel requires the runtime org.gnome.Platform/x86_64/3.32 which was not found
```

**Comment by bochecha** [comment]
> I even restarted the system, although I would not expect that to be required by a non-windows OS. :)

Modifying the env vars of a running process (your desktop session and all the processes it spawned) is not something that can be done simply and reliably when installing a package. So when you install the `flatpak` package, you need to restart your session so that the new env vars (see your first message) are set up. That's why other distros install Flatpak by default.

In any case, you can complain to your distro developers, that's unrelated to Glimpse.

> I still get the error, I'm not prompted to install the runtime.

Ok, so that's a bug in Flatpak.

The problem is you have Flathub configured as a system-wide remote but glimpse_devel as a per-user remote.

Somehow, when installing an app from a per-user remote, Flatpak only searches for the required runtime in per-user remotes, not in the system-wide ones. This is a bit disappointing. :slightly_frowning_face: 

If you manually install the platform from the system-wide remote though, then Glimpse can use it just fine:

```
$ flatpak install flathub org.gnome.Platform//3.32
$ flatpak install glimpse_devel org.glimpse_editor.Glimpse
```

**Comment by ihabunek** [comment]
Glimpse installed and running. Thank you a lot for your help.

**Comment by bochecha** [comment]
> > I still get the error, I'm not prompted to install the runtime.
> 
> Ok, so that's a bug in Flatpak.
> 
> The problem is you have Flathub configured as a system-wide remote but glimpse_devel as a per-user remote.
> 
> Somehow, when installing an app from a per-user remote, Flatpak only searches for the required runtime in per-user remotes, not in the system-wide ones. This is a bit disappointing. slightly_frowning_face

For the record, that's https://github.com/flatpak/flatpak/issues/2116#issuecomment-539517406
