### ISSUE TITLE
Include upstream names in Help > About > Credits?

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#179]
Currently we just list contributors for Glimpse in this window, but there is a case to be made for upstream contributions to be acknowledged in the UI.

If we choose to do so, I believe it would make sense to approach the upstream project to ask how they feel about us doing that. It may be that their own contributors disagree with our fork and don't want to be associated with it, or they may feel strongly that they should be acknowledged.

By preserving an original list of contributors with the code & the original GNU GPLv3 license we are still in compliance regardless of which way we go on this.

Additional reference: https://twitter.com/glimpse_editor/status/1182113975951118336

**Comment by TrechNex** [comment]
The other question would be how exactly we go about this. If we just mix our names with upstream names then it could they will just disappear into that huge list and either diminish our own contributions or look like we're trying to write ourselves into another project's history.

Writing a separate dialog window for this would probably have to be deferred until a later release.

**Comment by Member1221** [comment]
imho we could just add a link to the dialogue box with "Upstream Contributors" which just links to the ORIGINAL_AUTHORS list.

**Comment by TrechNex** [comment]
Confirming that this should wait until 0.2.0, as we will need to integrate changes for translators tab.

**Comment by TrechNex** [comment]
Closing as now duplicated by #228
