### ISSUE TITLE
Port Glimpse for the Raspberry Pi

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#182]
Tangentially linked to #181 

This device is wildly popular in schools. We should ensure it is possible to install Glimpse on Raspbian and the ARM architecture, and fix any bugs that emerge to ensure the experience is good.

**Comment by TrechNex** [comment]
I would also encourage us to make contact with the Raspberry Pi Foundation, as their feedback could dramatically improve this effort. It would also be wonderful to see Glimpse bundled with Raspbian by default, but I do not know if that is a reasonable aspiration or not.

**Comment by creepertron95** [comment]
@TrechNex Is there any ARM builds of Glimpse at the moment? I can test Glimpse on a Raspberry Pi 4 Model B.

**Comment by TrechNex** [comment]
I believe Flathub automatically produces ARM64 builds from our code, so you could try that to see if it works?

**Comment by TrechNex** [comment]
Confirmed that Glimpse runs on ARM64 variants of the Raspberry Pi, and devices like the Pinebook Pro.
