### ISSUE TITLE
Port Glimpse for ChromeOS

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#183]
Chromebooks are increasingly popular in US schools that provide each student with their own laptop.

Regardless of whether this turns out to be a bigger trend across OECD countries or not, we could eliminate another barrier to entry for teachers wanting to use our software in their classroom.

Tangentially related to #181

**Comment by BrainBlasted** [comment]
This should already be possible with ChromeOS's ability to run Linux apps, right?

**Comment by TrechNex** [comment]
Closing as this is already covered by Flatpak setup documentation
