### ISSUE TITLE
Consider basing on PhotoGIMP

### ISSUE THREAD

**Issue by probonopd** [glimpse-editor/Glimpse#193]
Consider basing on [PhotoGIMP](https://github.com/sudo-give-me-coffee/PhotoGIMP). It addresses the GUI quirks that have been criticized in the GNU Image Manipulation Program for a long time, and makes it easier to operate for users coming from other image manipulation applications.

**Comment by Member1221** [comment]
We plan on doing upstreamable changes for the hard fork phase; That project seems to not be geared thowards that and is directly modifying AppImages. We plan to support more than just AppImage. All in all it would be a lot of work with too little flexibility imho.

**Comment by TrechNex** [comment]
There is also the small matter of potentially getting sued by Adobe as well, particularly if our project matures to the point it's being chosen by schools/workplaces instead.

**Comment by TrechNex** [comment]
If you would like to get more involved with the UI redesign though, the wiki is a good starting point: https://wiki.glimpse-editor.org/index.php?title=Main_Page

There's also a Matrix channel the people involved with the UI rewrite that's happening in parallel are working on that I can add you to as well. :)

**Comment by TrechNex** [comment]
For reference, documented how to convert Glimpse Image Editor into PhotoGIMP here: https://github.com/glimpse-editor/Glimpse/wiki/How-to-Install-the-PhotoGIMP-Plugin

The legal issues remain the same, but there are some elements we could make use of. :)

**Comment by TrechNex** [comment]
Link to #412
