### ISSUE TITLE
OneDrive folder doesn't appear in file chooser

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#202]
Noticed by me while doing work on the Windows port, and someone else from upstream: https://gitlab.gnome.org/GNOME/gimp/issues/4165

I am not sure if this is fixable for 0.1.0, but it should definitely be fixed in 0.2.0 imho

**Comment by Member1221** [comment]
This is a GTK thing afaik. Basicly OneDrive is implemented in a way that makes it hard for GTK File dialogs to detect it.
