### ISSUE TITLE
Submit Glimpse to Flathub

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#218]
Issue link for any PRs we need to raise to facilitate this. Target date is Tuesday 19th November 2019.

**Comment by TrechNex** [comment]
Once we are code complete I will create a tag for this release in git and create the `glimpse-0-1` branch for any subsequent bugfix releases.

`dev-g210` will continue to be the dev branch

**Comment by bochecha** [comment]
App submitted for review in Flathub: https://github.com/flathub/flathub/pull/1268

I suggest we close this issue here, because the app won't be accepted in Flathub until we have 0.1.0 released, and unless you close this issue the 0.1.0 milestone will never be complete. :stuck_out_tongue:

**Comment by TrechNex** [comment]
Consider it done.
