### ISSUE TITLE
Splash screen has GIMP in window-title.

### ISSUE THREAD

**Issue by tastytea** [glimpse-editor/Glimpse#230]
**Describe the bug**

The splash screen has the window-title “GIMP-Start”. Locale is de_DE.utf8. I guess it has no title on some (or most) window managers, but on i3 it does.

**To Reproduce**
1. Install i3
2. Start i3
3. Start Glimpse
4. Look at splash screen

**Expected behavior**
I expect the title to be Glimpse-Start or something similar.

**Screenshots**
![screenshot_2019-11-22T18-44-42](https://user-images.githubusercontent.com/3681516/69448443-d597cd00-0d58-11ea-8e6f-4ea08f168175.png)

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Version 2.6

**Comment by Member1221** [comment]
Thanks for catching that, will be fixed in next patch
