### ISSUE TITLE
Restore The "Color" Icon Theme

### ISSUE THREAD

**Issue by BrainBlasted** [glimpse-editor/Glimpse#232]
**Is your feature request related to a problem? Please describe.**
The legacy icon theme does not have great contrast, and the icons are old and blurry.
The Color icon theme fixes all of these issues.

**Describe the solution you'd like**
Restore the Color icon theme.

**Additional context**
Color Theme:

![image](https://user-images.githubusercontent.com/29347290/69450281-a316b180-0d11-11ea-8222-64ed0e35c32c.png)

Legacy Theme:

![image](https://user-images.githubusercontent.com/29347290/69450315-b590eb00-0d11-11ea-8914-5f2030484d60.png)

**Comment by TrechNex** [comment]
I'm suggesting this should be a 0.2.0 candidate on the grounds it's a hassle to re-add all the assets to the WiX manifest we use for the Windows installer.

**Comment by TrechNex** [comment]
Bringing this in as a 0.1.x candidate as the only real hold up to this is me having to fix the WiX Toolset manifest. But given the importance of including it I think it's worth expediting.
