### ISSUE TITLE
Rename build to build-aux

### ISSUE THREAD

**Issue by hellsworth** [glimpse-editor/Glimpse#233]
**Is your feature request related to a problem? Please describe.**
There is no functionality problem. Rather, it is common for GNOME projects to have a `build-aux` folder. If this project decides to follow GNOME conventions, then this is a logical change to make.

**Describe the solution you'd like**
Change the name of the `build` folder to be `build-aux`.

**Comment by TrechNex** [comment]
Change is being made on dev branch, so expecting this to be implemented in the 0.2.0 release.

**Comment by TrechNex** [comment]
This happened in 0.1.2
