### ISSUE TITLE
UI doesn't remember configuration

### ISSUE THREAD

**Issue by proxygoat** [glimpse-editor/Glimpse#237]
What I did: Started Glimpse. Repositioned and resized window. Exited Glimpse. Restarted Glimpse.
What I expected to happen: Glimpse restarted in size and position at last exit.
What actually happened: Glimpse restarted in full-screen mode.

**Comment by TrechNex** [comment]
I am unable to reproduce this using our Linux flatpak on the GNOME desktop. I will attempt to do so on my Windows 10 development machine.

(FWIW the correct "Save window positions on exit" checkbox is in Edit > Preferences > Windows Management)

**Comment by TrechNex** [comment]
We will look into this as part of our beta testing for 0.1.2

**Comment by TrechNex** [comment]
Passing to 0.2.0 as we should check if this problem has already been resolved by upstream first.

**Comment by proxygoat** [comment]
I stumbled across org.gnome.mutter.auto-maximize, which is enabled by default and auto-maximizes nearly-monitor-sized windows. Disabling this setting renders this a non-issue.
