### ISSUE TITLE
German About screen ("Info") says "Die Internet-Seite von GIMP öffnen"

### ISSUE THREAD

**Issue by rschr** [glimpse-editor/Glimpse#238]
It links to the Glimpse website, though.

(Glimpse 0.1.0, Linux, Flatpak, on Mint 19.2)

**Comment by Member1221** [comment]
Yeah, general problem; happens for other languages too.
Marking this as a bug.

**Comment by TrechNex** [comment]
Confirmed that this tooltip text still needs to be fixed. It was not resolved in #263

**Comment by TrechNex** [comment]
Closing as this was resolved after all. Further translations may still need to be made to tooltips though.
