### ISSUE TITLE
When to wait for localization of an interface in other languages?

### ISSUE THREAD

**Issue by mrkaban** [glimpse-editor/Glimpse#240]
Hello, thank you very much for the program! I sincerely wish you success in your development! I liked it. I added it to my free software site (GNU GPL and similar licenses) - [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0/%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D1%8B/glimpse-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9.html). It is in Russian, attendance is approximately 1200 people a day, among them are many teachers.

Therefore, I want to ask a question that visitors to my site will fall asleep me when to wait for the translation of the program into Russian? in GIMP this translation was, can it be taken from there?

**Comment by Member1221** [comment]
There should already be russian translations (taken from upstream) in Glimpse for Russian.

**Comment by BrainBlasted** [comment]
One thing to keep in mind is that due to some trouble with translations, many still have references to the upstream GNU Image Manipulation Program

**Comment by mrkaban** [comment]
I do not see a Russian translation. Here is a screenshot, in the settings only English localization.
![111](https://user-images.githubusercontent.com/14289360/69497089-9f4e7f00-0f0b-11ea-830f-6d0204cc6fe4.jpg)

**Comment by Member1221** [comment]
If you set it to System Language and if your system is in Russian it should load the Russian translation; otherwise we'll need to compile with full translation listing. @TrechNex

**Comment by TrechNex** [comment]
Confirmed that this bug applies on Windows and Linux. It would be interesting to see if it's also present in upstream.

My guess is that it may have more to do with how we package and distribute the application. I am tagging in @bochecha as I am not sure how languages are handled in Flatpaks, and I will need to read up on how languages are fetched on Windows so I can fix the installer if needed.

**Comment by TrechNex** [comment]
In the meantime it could be worth taking at look in the `%appData%` directory on Windows. The `Glimpse` and `Gimp` folders there are fairly similar, and we can figure out which files are missing that should be present.

**Comment by Member1221** [comment]
On Windows we need to copy `$HOME/w64/usr/$HOST/sys-root/mingw/share/pkgconfig/iso-codes.pc` to `$HOME/w64/usr/$HOST/sys-root/mingw/lib/pkgconfig` before running autogen to get language dropdown support. @TrechNex

**Comment by TrechNex** [comment]
I will find an evening this week to try out that fix :)

On the flatpak currently I only see system, en_CA, en_GB and en_US. Not sure if that's expected or not.

**Comment by bochecha** [comment]
> I do not see a Russian translation. Here is a screenshot, in the settings only English localization.
> ![111](https://user-images.githubusercontent.com/14289360/69497089-9f4e7f00-0f0b-11ea-830f-6d0204cc6fe4.jpg)

How did you install it and what is your system locale?

**Comment by mrkaban** [comment]
launched "glimpse-0.1.0-unsigned.msi" as administrator and installed. Windows 10 x64 operating system. Do I need to provide you with any files or folders?

**Comment by bochecha** [comment]
> launched "glimpse-0.1.0-unsigned.msi" as administrator and installed. Windows 10 x64 operating system. Do I need to provide you with any files or folders?

No, it's just that you hadn't said, so I was wondering whether the problem you had was on Windows or on Linux. (with Flatpak)

As far as I can see, the translations are working just fine with the Flatpak build.

(Since this is a Windows issue I'm going to unsubscribe from it, do CC me if you find something similarly wrong with the Flatpak build)

**Comment by TrechNex** [comment]
I will look into this. It's possible that the current Windows packaging process doesn't pull in all the right files.

**Comment by TrechNex** [comment]
Have confirmed that the reason the languages are not available on Windows is the WiX manifest file does not collect them at packaging time when we're building the installer.

This was because when I packaged 0.1.0 I hadn't run `make update-po` at any point, so missed that we needed the **share\locale** folder.

**Comment by mrkaban** [comment]
Thanks! We will wait for the correction!
