### ISSUE TITLE
Glimpse doesn't launch

### ISSUE THREAD

**Issue by WenLau72** [glimpse-editor/Glimpse#249]
**Describe the bug**
When trying to launch, I get the splash screen where it says 'Looking for Data Files'. Once it reaches 'Modules' it stops and then shuts down after about 20 to 30 seconds.

**To Reproduce**
Click on program to launch (both As Administrator and not).

**Expected behavior**
Program launch.

**Desktop**
 - OS: Windows
 - Version 10 (just updated to 1909, no more updates available to me) 64bit

**Verbose Logs** (Post logs from running the application with the `--verbose --console-messages` flags)
Have no idea how to do this, would need detailed instructions

**Additional context**
I had been using the Beta Release with no problem. I deleted the folder in %AppData% (Local Folder and Roaming); Uninstalled and Reinstalled; Added exception to Windows Defender; Ran as Administrator; Checked for and installed all Windows updates available. It still does not launch for me.

**Comment by TrechNex** [comment]
a) Can you make sure the original BETA is fully uninstalled?
b) Fully uninstall your current Glimpse installation (also `%appData%\Glimpse`)
b) Once that is done, we have a new "signed" installer set to be announced this evening: https://github.com/glimpse-editor/Glimpse/releases/download/v0.1.0/glimpse-0.1.0.msi

Let us know if that resolves the issue. If not then we will need to go through how to get the verbose console output as that could be a bug in the way we've packaged things.

**Comment by WenLau72** [comment]
Thanks for your suggestions.

I went through them all, and unfortunately, I still only get to 'Modules' then it seems to work for between 20 to 30 seconds and closes. I had not thought to uninstall the BETA previously, but did so this time. I then uninstalled and used the 'signed' installer.

I also double-checked that I had the exclusions set up, and they were.

**Comment by WenLau72** [comment]
Just a quick follow-up. I figured out how to run the --verbose --console-messages, but the window disappears when the splash screen does, so I can't copy the output to display here. I haven't been able to figure out if the log is saved somewhere, so I would need that info or how to leave the window open/save the information

**Comment by Member1221** [comment]
If you have any drawing tablets connected, try disconnecting them before launching glimpse. @WenLau72 

(Might be related to #229)

**Comment by WenLau72** [comment]
Thanks for the suggestion. I'm pretty sure the tablet wasn't plugged in, but I double-checked and tried again. No luck though. It does sound very much like #229 though.

**Comment by WenLau72** [comment]
Reading through the other issue, I figured out how to save to a file. I'm not sure how attaching files works, but I'll give it a shot and hope it works.
[output.txt](https://github.com/glimpse-editor/Glimpse/files/3914786/output.txt)

**Comment by TrechNex** [comment]
As an FYI there do seem to be bugs getting raised upstream about people having trouble launching the application when tablets are connected or installed, so this may not be unique to Glimpse.

https://gitlab.gnome.org/GNOME/gimp/issues/2738
https://gitlab.gnome.org/GNOME/gimp/issues/4284
https://gitlab.gnome.org/GNOME/gimp/issues/3497

It does warrant further investigation in case we can find a solution.

**Comment by TrechNex** [comment]
Tagging to #244 as it's possible some fixes may have been made for 2.10.14 (we are based on 2.10.12), but it's likely we could have to wait until a later 2.10.x release.

**Comment by WenLau72** [comment]
I tried to open the program this morning, as I have done at irregular intervals since I've installed, and to my great surprise, it suddenly opened.

I haven't changed anything on my computer, between when I tried yesterday and this morning. They did install "Security Intelligence Update for Windows Defender Antivirus" overnight, but since I had turned off Windows Defender during several of my previous trials, I'm not sure if that could be it. I'll give it a day or so, and if it stays opening, we can probably consider this closed.

I'm not sure if at that time I would be the one to "close"? Please let me know.

**Comment by TrechNex** [comment]
If this issue crops up again @WenLau72 let us know. I'm happy for you that it does now work though :)

**Comment by luiandresgonzalez** [comment]
Hi, I am having this same issue. Tried reinstalling and nothing. The splash screen shows up but crashes at apparently different moments of startup. Is there a way to provide debug details?

**Comment by TrechNex** [comment]
@luiandresgonzalez can you confirm if GNU Image Manipulation Program 2.10.18 runs on your system?

If so, hang fire for Glimpse Image Editor 0.1.4 beta later this month. We have backported a number of important Windows fixes from upstream, so it's possible that will resolve your problems.

**Comment by luiandresgonzalez** [comment]
@TrechNex I confirm I have version GIMP v2.10.6. 
I will wait then, thanks!
