### ISSUE TITLE
Glimpse Gimp remnant

### ISSUE THREAD

**Issue by frazerturk** [glimpse-editor/Glimpse#250]
Still says GIMP in the colour picker for the text tool.

Nothing major, but I know (or I think that's what I read when I installed Glimpse the other day) that the Glimpse team is intent (rightly) on removing all traces of GIMP from the product.

x-special/nautilus-
![Glimpse Bug 001](https://user-images.githubusercontent.com/58343676/69887669-18f0bf00-12b6-11ea-8ec7-1d5d9664b5d0.jpg)

**Comment by TrechNex** [comment]
Still to be fixed. I will need to investigate which plugin or section of the code the colour picker is spawned from, then figure out how to change the logo and tooltip text.
