### ISSUE TITLE
Palette files still use 'GIMP' in the header

### ISSUE THREAD

**Issue by ryliejamesthomas** [glimpse-editor/Glimpse#256]
Hey!

Just messing round with palettes and noticed that custom palettes are still labelled as 'GIMP Palette' in their header. Example file I created: `SG-x000.gpl` in `~/.config/Glimpse/0.1/palettes/`:

```
GIMP Palette
Name: SG-x000
Columns: 15
#
  0   0   0	Black
 33 200  66	Medium Green
 94 220 120	Light Green
 84  85 237	Dark Blue
125 118 252	Light Blue
212  82  77	Dark Red
 66 235 245	Cyan
252  85  84	Medium Red
255 121 120	Light Red
212 193  84	Dark Yellow
230 206 128	Light Yellow
 33 176  59	Dark Green
201  91 186	Magenta
204 204 204	Gray
255 255 255	White

```

**Comment by TrechNex** [comment]
Is this visible from the front end UI? Also are there any ramifications for compatibility if this is changed?

Answers to both of those questions will determine how we need to fix that. :)

**Comment by ryliejamesthomas** [comment]
As-far-as-I-know it's only visible if you open in a text editor (which is a task I seem to end up doing every now and then).

Removing or replacing the `GIMP Palette` line stops Glimpse from loading the palettes :( (You get the error `In line 1 of palette file: Missing magic header.`)

**Comment by TrechNex** [comment]
In that case for now we'll mark this as a "won't fix" because while we could make code changes to make that work, it would probably break compatibility with upstream. For as long as we remain a fork, we should avoid that wherever possible imho.
