### ISSUE TITLE
Missed a plugin rename

### ISSUE THREAD

**Issue by XenonFiber** [glimpse-editor/Glimpse#267]
![image](https://user-images.githubusercontent.com/28912578/73044364-f353e200-3e2e-11ea-83e5-74970dd14b6c.png)

**Comment by TrechNex** [comment]
Thank you for this, it's definitely an interesting one to deal with. If anyone has alternative name suggestions for it, drop them in the comments below :)

cc @chaomodus in case this plug-in can be removed in 0.2.0 when we add G'MIC #262

**Comment by Member1221** [comment]
"Artistic Effects..."

**Comment by jgamble** [comment]
"Cubism" and "Van Gogh" are already in the menu, so why not just 'Impressionism"?

**Comment by TrechNex** [comment]
I've tagged this to 0.1.1 (the bug-fix release I'm currently working on) as I'm doing a lot of translation fixes anyway. This could be another quick fix :)

**Comment by TrechNex** [comment]
My intended fix is to just change it to "Impressionist...". That neatly fixes the problem and is still similar enough that people know what it is :)
