### ISSUE TITLE
Plugins and scripts. (Same issues as everyone else)

### ISSUE THREAD

**Issue by casperl** [glimpse-editor/Glimpse#273]
In my case there is one script I use a lot - National Geographic.

Under settings>folders I added a directory outside of the SNAP sandbox as a script folder, but that seemed to have no results, the scripts in Glimpse-Editor does not reflect those scripts.

I then tried to add the natgeo script manually, but the Glimpse snap folder is a read-only file system.

I suppose I can boot linux in a recovery mode and add those scripts to into the snap folder and reboot.  But I suspect that will only work until the next time a snap refresh takes place — if it works at all.

I am stuck, and the only alternative is to run snap giimpse-editor remove and re-install and older GIMP version from the ubuntu repositories.

**Comment by Member1221** [comment]
cc @hellsworth

**Comment by hellsworth** [comment]
Hi @casperl , snaps are designed to run scripts inside the snap sandbox only, otherwise it's kind of a poor sandbox :) Similarly we want to keep the snap sandbox safe from folks putting scripts - that could be nefarious - inside the sandbox. So you won't be able to run this script in the snap version of Glimpse.

However, you can always just [build and install Glimpse](https://wiki.glimpse-editor.org/index.php?title=Building_Glimpse/Linux) (not the snap). This is not as daunting as you might think so I encourage you to go check out the steps for your setup and give it a go. If you have any issues at all, the Glimpse community is here to help :)

**Comment by TrechNex** [comment]
As an FYI the Glimpse project doesn't directly support the Snap package, so it's great to see @hellsworth picking up this bug :)

You could try putting the script folder in your home directory. One would assume if the sandbox grants permissions to open/save files from there it can also fetch scripts from there too?

The download method we directly support is Flatpak, and we intend to provide an AppImage very soon: https://glimpse-editor.org/downloads/

**Comment by hellsworth** [comment]
I took a closer look and it appears to be essentially a plugin in the form of a script: [National Geographic Script](https://gimper.net/resources/national-geographic-script.563/). I was able to use this script inside the glimpse-editor snap as long as I put the .scm files in the scripts folder located within the snap. @casperl here are the steps that worked for me with the glimpse-editor snap. Please let me know if this doesn't work for you.

In my Edit->Preferences->Folders->Scripts , I see two folders listed by default:  
/home/heather/snap/glimpse-editor/x1/.config/Glimpse/0.1/scripts  
/usr/share/glimpse/2.0/scripts

If you grab the National Geographic Script and unzip it, there are two scm files:  
elsamuko-national-geographic-batch.scm 
elsamuko-national-geographic.scm

Then copy those files to the /home/<user>/snap/... scripts folder. Then refresh the list of available scripts with Filters->Script-Fu->Refresh Scripts . Now the National Geographic script should be found in the Filters->Generic menu. Then I imported a photo (I used an [example pic](https://www.flickr.com/photos/28653536@N07/2885742736/) from the Nat Geo Script page). Once imported, I went and selected the script from Filters->Generic->National Geographic and it ran on the picture. The end result was a different look to the picture and there are several layers that have been broken out and are visible in the layers list on the right.

**Comment by hellsworth** [comment]
I'm going to close this issue. Please re-open if you still have issues using scripts in the glimpse-editor snap.
