### ISSUE TITLE
Travis CI build breakage question

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#275]
Unfortunately the Travis CI validation check currently breaks! Adding a "dummy release" or commenting out the "releases" tag in the Flatpak metadata does not fix the problem.

I believe there is something about `desktop/test-appdata.sh.in` that is preventing the test from passing, and that it is related to me bumping the version in dev branch to 0.1.1.

It seems to be running a modulo operation against the micro version and following upstream behaviour. eg. even-numbered microversions = a stable release, odd-numbered microversions = an unstable release.

I am okay with following that convention, but if that is the case we need to understand what is needed in `desktop/org.glimpse_editor.Glimpse.appdata.xml.in.in` to pass the validation tests.

**Comment by TrechNex** [comment]
It is very strange that this error was not triggered in the PR before I merged into `dev-g210`, so that is something we will need to be aware of for future releases.

I have initially assigned to @bochecha as they initially set up the Flatpak metadata and validation checks. :)

**Comment by bochecha** [comment]
Do you have a link to a failure?

**Comment by TrechNex** [comment]
From `dev-g210` branch: https://travis-ci.org/glimpse-editor/Glimpse/builds/645371855?utm_source=github_status&utm_medium=notification

My previous failed attempts at troubleshooting are here (click the red "X" to get the link): https://github.com/glimpse-editor/Glimpse/pull/274

**Comment by bochecha** [comment]
Is that the first commit which failed the tests? Did you try looking at the `desktop/test-suite.log` file as suggested in the error output?

**Comment by TrechNex** [comment]
The minor version change was made in this commit: https://github.com/glimpse-editor/Glimpse/commit/8594f33d356dda6ec292ad16620d01a3856802b4

The error did not crop up until I merged the associated PR (which was passing) into `dev-g210`, which is why it came as a surprise to me 😅 

I have not seen the output of that log as I have not run the step locally on a build machine yet. That output is not displayed in the Travis CI web UI as far as I can tell. (I can try doing that, but I won't be able to until some time this evening UK time)

**Comment by TrechNex** [comment]
There was also an earlier fix applied to Travis CI btw to fix an earlier problem with it running the build. I don't think that is related to this issue, but for reference: https://github.com/glimpse-editor/Glimpse/pull/268/commits/1823b231e4dbaf234568b94382eda6b9c9be4db2

**Comment by bochecha** [comment]
This is what breaks the appdata validation:

```
FAIL: test-appdata.sh
=====================

/home/travis/build/glimpse-editor/Glimpse/desktop/org.glimpse_editor.Glimpse.appdata.xml: FAILED:
• url-not-found         : <screenshot> failed to connect: Cannot connect to destination [https://glimpse-editor.org/flatpak/0.1/dark-theme1.png]
• url-not-found         : <screenshot> failed to connect: Cannot connect to destination [https://glimpse-editor.org/flatpak/0.1/light-theme2.png]

Validation of files failed
```

Indeed, the website isn't accessible, I can't open it in Firefox. Oops. :laughing: 

I found the issue thanks to #276, which prints the content of the `test-suite.log` file.

**Comment by TrechNex** [comment]
Thank you for troubleshooting this @bochecha. I've rebooted the server that runs our website and now re-running the test via your PR. If that is the fix then it'll be merged in to dev branch so we can see better details in future.

I am also kind of concerned that no one had any idea our website was down, so if that is fixed we'll need to find some kind of service like pingdom or something to alert us when that happens again.

(Building less flaky servers in on @chaomodus's to-do list! The one we use at the moment was built by me in haste)

**Comment by TrechNex** [comment]
Closing as now fixed 🎉
