### ISSUE TITLE
Will we support "AppCenter for Everyone"?

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#277]
### Brief Summary
Our current policy on supporting elementaryOS is the same as supporting any other Linux distribution: We direct users to install the Flatpak we produce for Flathub, and are ready to assist distro maintainers that want to package our application.

The described new system seems to have switched from Debian packaging to Flatpak, and could bring the elementaryOS store to other Linux distributions. This could make supporting that platform more compelling for us, but we would need to investigate the technical requirements.

There is also the secondary motivation that it could be a new avenue of monetization for our project because of its "pay what you want" model. We would need to think carefully about how that would fit with our existing Open Collective and how we would use any donations from that platform.

This issue is a call for opinions about whether people think this is a good or bad idea, and record the outcome of discussions about this.

### More Details
IndieGoGo campaign: https://www.indiegogo.com/projects/appcenter-for-everyone#/
YouTube video from The Linux Gamer: https://www.youtube.com/watch?v=E_Xz_SmBPzU

**Comment by cassidyjames** [comment]
We love Glimpse and frequently use it at elementary for editing photos (via the Flathub Flatpak). :) 

One large caveat for Glimpse: AppCenter will have many of the same [publishing requirements](https://github.com/elementary/houston/wiki/Before-You-Publish#requirements) as today, particularly that apps must be GTK3 (or GTK4 once that's released). This means today, Glimpse is probably better off continuing to support Flathub as the preferred installation method. However, if/when a GTK3 or GTK4 UI port happens, Glimpse could be submitted to AppCenter and made available via the pay-what-you-want system on any Flatpak system.

**Comment by TrechNex** [comment]
Unfortunately we don't have the resources to do the GTK2 to GTK3 port ourselves, so that will most likely happen when we re-base on GNU Image Manipulation Program 3.0.x in Glimpse Image Editor 1.0.0. We understand from upstream that will happen either towards the end of this year or early next year.

I know that might disappoint some people reading this, but the positive side is that this gives us plenty of time to answer the project questions I outline and review the finished product.  :)

**Comment by BrainBlasted** [comment]
I think that it would be good to support it once we do have a GTK3/4 edition of Glimpse. It shouldn't take much effort as we could probably re-use our flatpak manifest from Flathub.

**Comment by GammaGames** [comment]
I have it installed through AppCenter already thanks to its flathub support, I would definitely pay a bit, especially to support the rewrite!

**Comment by TrechNex** [comment]
Closing this for now as we do not have any idea when upstream plan to release GNU Image Manipulation Program 3.0, lack the capacity to do the GTK3 migration ourselves, and are unlikely to re-base onto 3.0 when it does happen.

Our current plan is to stick to the 2.10.x base for the time being, make our UI changes, then eventually (in 2+ years) migrate to a new image editing application called Glimpse NX that @Member1221 is heading up.

Given we are not permitted to publish in the AppCenter with GTK2, that means we will have to continue to instruct Elementary users to install via Flathub for the time being. We can then revisit this issue once Glimpse NX is ready for primetime.

**Comment by cassidyjames** [comment]
@TrechNex that sounds completely reasonable. And installing from Flathub works well in elementary OS—even delivering updates through AppCenter. So it seems like a good option for now.
