### ISSUE TITLE
Port this project from Gitlab to Github

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#3]
This would involve changing all files and folders that facilitate the use of Gitlab to their equivalents in Github.

eg. Issue templates, CIT build scripts, etc.

**Comment by TreacherousNexus** [comment]
Also linking to issue #2 as there might be some overlap with this task.

**Comment by ChameleonScales** [comment]
I'm no developer but afaik Gitlab is a little more ethical and it doesn't seem to be lacking in features.
What's the reason behind this migration?

**Comment by TrechNex** [comment]
There wasn't one. The original source code was forked from a Gitlab server hosted by GNOME project, hence why the porting/cleanup effort was necessary.

This was a choice made early on for entirely practical reasons (eg discoverability, usability, etc). We do periodically check to see what our community thinks of Github and our use of it on Matrix, but the only real objections we get are the occasional random on social media telling the project off for using it every so often.

**Comment by TrechNex** [comment]
Locked as comment seems like a sensible thing to add to FAQs page. Has also been mentioned here on social media: https://bobadon.co.uk/@glimpse/102565685333816598
