### ISSUE TITLE
Pre-bundle colourful icon theme

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#301]
### Is your feature request related to a problem? Please describe
This unique icon theme looks amazing and groups together icons by colour. We would need to check to see how icons appear in their default layout though.

### Describe the solution you'd like
![0d6c2e9f30f465f0](https://user-images.githubusercontent.com/45732696/74818290-474ecb00-52f6-11ea-9604-696bbf19fb43.png)

### Describe alternatives you've considered
N/A

### Additional context
Original toot link: https://mastodon.art/@glimpse/103684678538171407

**Comment by TrechNex** [comment]
Currently tagged to 0.1.2, but if icons need to be rearranged to accommodate this it may need to be pushed out to a later release.

**Comment by TrechNex** [comment]
Kicked out to 0.2.0 as I think we could shift the layout around to accommodate this.

I have mirrored the repository to here, but because it's on Codeberg we will need to manually update it: https://github.com/glimpse-editor/Colored-Tool-Icons-for-GIMP-and-Glimpse

**Comment by TrechNex** [comment]
Discussions have started about potentially using this as the "default" icon theme in 0.2.0. To accommodate that we would need a better dark theme, and code changes to rearrange the default layout.

A big benefit of this is it will differentiate us from upstream in a very visual way that doesn't also alienate & confusing existing users.

**Comment by GarkGarcia** [comment]
Wouldn't it be more consistent if the logo colors were used for icon theme too? We could group icons in a similar manner, but tint them with [our established branding colors](https://github.com/glimpse-editor/branding#colors)

**Comment by TrechNex** [comment]
That is potentially a good idea. Main issue is that those colours weren't chosen with UI accessibility in mind, so it would need some testing to make sure they're suitable.

cc @jaames as they made the logo and is helping with UI design stuff

**Comment by GarkGarcia** [comment]
Indeed, accessibility is a huge concern. Still, even if those colors cannot be used _as is_, maybe we should try to adapt them to fit the accessibility requirements.

**Comment by TrechNex** [comment]
The other thing I'm concerned about is that people with colour blindness are likely to have trouble differentiating between green and blue, regardless of which hue we choose. 🤔 

I think the project should wait until I re-base the source code on 2.10.18. That's due to release any day now, and there are some very cool UI changes that could go some way towards resolving this problem.

**Comment by TrechNex** [comment]
For reference, tracking issue for 2.10.18 rebase: #189

**Comment by GarkGarcia** [comment]
> The other thing I'm concerned about is that people with colour blindness are likely to have trouble differentiating between green and blue, regardless of which hue we choose.

That's an interesting point. Wouldn't that be an issue with the [neon colored icon theme](https://github.com/glimpse-editor/Colored-Tool-Icons-for-GIMP-and-Glimpse) too? [This](https://medium.theuxblog.com/how-to-design-for-color-blindness-a6f083b08e12) may relevant.

We could also have the current colorless icon theme installed by default, so user with color blindness could simply disable the colored icon theme.

> I think the project should wait until I re-base the source code on 2.10.18. That's due to release any day now, and there are some very cool UI changes that could go some way towards resolving this problem.

Makes sense.

**Comment by GarkGarcia** [comment]
This is off-topic, but since we are discussing changing the default icon theme we could also consider redesigning some of the icons to better integrate with the logo aesthetics. For example, we could smooth out some corners in the default GIMP theme.

**Comment by jaames** [comment]
So, I tried playing around with those icons a bit. These colors all have a AAA contrast ratio against the background (`#0f1011`) while still somewhat keeping to the pastel-y vibe of our branding colors. I also made the grey icons pure `#ffffff` so they have better contrast:

<img width="158" alt="Screenshot 2020-02-23 at 15 42 01" src="https://user-images.githubusercontent.com/9112876/75115021-0d155e80-5653-11ea-9083-97d67a4f3116.png">

But tbh I don't think that grouping things solely by color is really a good idea if the goal is accessibility, since it's gonna be difficult to find a selection of colors that works for every type of color blindness. Ideally there should be some kind of visual separator (like a border) between groups as well?

----

> This is off-topic, but since we are discussing changing the default icon theme we could also consider redesigning some of the icons to better integrate with the logo aesthetics and branding guidelines. For example, we could smooth out some corners in the default GIMP theme.

Yeah, that's definitely something we should consider to differentiate ourselves from upstream. It wouldn't hurt to redraw some with clearer visual metaphors, too. :)

**Comment by GarkGarcia** [comment]
> So, I tried playing around with those icons a bit. These colors all have a AAA contrast ratio against the background (`#0f1011`) while still somewhat keeping to the pastel-y vibe of our branding colors. I also made the grey icons pure `#ffffff` so they have better contrast:

Those look great!

> Yeah, that's definitely something we should consider to differentiate ourselves from upstream. It wouldn't hurt to redraw some with clearer visual metaphors, too. :)

Absolutely! I think this is something that could be easily improved, since it's a cosmetic change after all.

**Comment by malabo1990** [comment]
![image](https://user-images.githubusercontent.com/23149831/75189034-a5900980-574d-11ea-9c0f-7194963c7d8d.png)

I have not finished processing ... I am looking at other software such as psd, affinity, pixelmator, corel, blender, gimp and many more ... I have also seen some behance with their design "concept redesign" icon are very interesting ...

I hope if you liked it.

Contribute ideas here. Please

**Comment by malabo1990** [comment]
![image](https://user-images.githubusercontent.com/23149831/75260379-d45bbd80-57e9-11ea-9c2f-10668340a0b7.png)

The design icon is increased ... I would like you to comment on you ideas

**Comment by TrechNex** [comment]
Thank you for the suggestions @malabo1990 :)

We will examine these in more detail after 0.1.2 is released on Monday. 👍

**Comment by GarkGarcia** [comment]
[This](https://github.com/glimpse-editor/Glimpse/issues/88) may be relevant. Perhaps this issue should be marked as duplicate?

**Comment by malabo1990** [comment]
![image](https://user-images.githubusercontent.com/23149831/75388280-fab25380-58e4-11ea-93a3-fd442c837e42.png)

**Comment by TrechNex** [comment]
I'm inclined to agree with @GarkGarcia that this is technically a duplicate of #88 

I won't close this issue though as we have some interesting suggestions here we should take into account imho.

**Comment by GarkGarcia** [comment]
To be honest, I don't think separating icons by category would work. The arrangement of the icons depends on the width of the tool box (which is configurable by the user), so icons of different colors could end up in the same row.

If we went the _visual separator_ rout a similar problem arises: we don't have precise control over the width of the toolbox, so icons of different categories could end up in the same row, making it impossible to separate them in rectangular boxes without potentially introducing some awkward white-space.

In my option, there's two ways we could handle this:

* Fix the width of the tool box. Most visual editors do that anyways.

* Abandon this idea altogether. Frankly the issues we have with the toolbox right now doesn't have much to do with theming. Beside, I've never seen a visual editor that separates tools by category in the toolbox. If the user wants to do so, he's free to use a custom icon theme as customize the tool box to his taste.

**Comment by BrainBlasted** [comment]
> If we went the visual separator rout a similar problem arises: we don't have precise control over the width of the toolbox, so icons of different categories could end up in the same row, making it impossible to separate them in rectangular boxes...

Not necessarily? As the width expands or shrinks, the layout of the sections and wrap or unwrap as needed. At the highest width they'd be spread out across one line.

I do think fixing the with would be the cleanest solution on that case, though.

> Beside, I've never seen a visual editor that separates tools by category in the toolbox.

Just because something hasn't been done doesn't mean it can't be done :)

**Comment by GarkGarcia** [comment]
> Not necessarily? As the width expands or shrinks, the layout of the sections and wrap or unwrap as needed. At the highest width they'd be spread out across one line, with the next section being a line below.

Fair enough. That's what i meant by _introducing awkward white-space_, but it doesn't seem awkward after all.

> I do think fixing the with would be the cleanest solution on that case, though.

I'm inclined to going that route too. I think combining visual separators (as decribed by @BrainBlasted above) with a default configuration that fixes the width of the toolbar (the user could opt-out in the settings menu or something) is the ideal solution.

> Just because something hasn't been done doesn't mean it can't be done :)

Sure, I'm just saying we're not lagging behind in that department.

**Comment by TrechNex** [comment]
I'd suggest people spend some time experimenting with 2.10.18. It's quite possible that this icon pack is a solution for an old problem, because the icon grouping that's been introduced provides that "visual" mechanism of grouping things together anyway.

**Comment by cristianovitorino** [comment]
> This could lead to some interesting new ideas though. :)

I'm working on something on the moment : ) I'll post the idea as soon as it's ready on #88 since this is a duplicate.

**Comment by AwesamLinux** [comment]
I like the idea of new modern colorful toolbar icons. It would be good for both branding and practical purposes. A subtle pastel color scheme like what @jaames came up with, would look nice and functional, also look distinctly different.

Considering color-blindness was brought up, I agree that grouping by just color alone should be avoided. A combination of color and other visual cues would be optimal.

**Comment by TrechNex** [comment]
Closing as this has been superseded by the changes we inherited in 2.10.18. We should open a new issue for new icon packs.
