### ISSUE TITLE
Update splash screen for Glimpse Image Editor 0.2.0

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#304]
### Is your feature request related to a problem? Please describe
The current splash screen was always intended as a placeholder until we started changing the UI.

### Describe the solution you'd like
Once we are happy with the new UI layout, theme and icon pack, we should create a new splash screen that matches it well.

### Describe alternatives you've considered
Leaving the current splash screen as-is.

### Additional context
I think as we'll be shifting to a dark theme with neon coloured icons in the toolbar, I think it would be cool to factor that in to the splash screen we ultimately go with. 

I think this will be the subject of wider discussion within the project and we can get our resident art/design people involved with it.

**Comment by GarkGarcia** [comment]
It would be cool if we could find an image produced with Glimpse. Perhaps we could host a small contest on `#glimpse:matrix.org` to find a suiting image?

**Comment by GarkGarcia** [comment]
If we choose to go that route, I'm available to take care of organizing the contest.

**Comment by TrechNex** [comment]
This was covered in #370 but I can reopen it if @cristianovitorino @GarkGarcia and @jaames want to have a crack at doing something different. Personally I think what we have now is sufficient.
