### ISSUE TITLE
Split out libraries to submodules

### ISSUE THREAD

**Issue by Member1221** [glimpse-editor/Glimpse#32]
Having everything in one repository makes quite the mess.

We should probably split everything out in to seperate repositories, then use meson to build each repository/submodule as neccesary.

**Comment by TrechNex** [comment]
Meson has been dropped for 1.0.0 stream, but I think this is still worth doing.

**Comment by TrechNex** [comment]
Duplicate of #33

**Comment by Member1221** [comment]
@TrechNex i'd more say #33 is a duplicate of this issue, since i'm also refering to libgimp, etc.

**Comment by TrechNex** [comment]
Apologies, I got muddled up between the two :sweat_smile:

**Comment by TrechNex** [comment]
I also think it'd be sensible to add the glimpse-editor/glimpse-helper-scripts repo as a submodule as well to help people figure out the build process.

**Comment by TrechNex** [comment]
This has been completed in dev-g210 branch
