### ISSUE TITLE
Main app icon: bad contrast on dark backgrounds

### ISSUE THREAD

**Issue by Feichtmeier** [glimpse-editor/Glimpse#323]
### Describe the bug
The app icon's shape becomes invisible on a dark background

### To Reproduce
Open gnome shell and search for the Glimpse editor

### Expected behavior
A soft highlight of the baseplate could help

### Screenshots
![Bildschirmfoto von 2020-03-03 21-38-48](https://user-images.githubusercontent.com/15329494/75817545-946f7a00-5d97-11ea-94b6-0b3e3871c4f8.png)

### Desktop (please complete the following information)
Ubuntu - gnome shell 3.35.91

**Comment by TrechNex** [comment]
cc @jaames the original creator of the logo as they may have design guidance on this.

Also for reference: https://github.com/glimpse-editor/branding

**Comment by Feichtmeier** [comment]
Cool!
The app icon itself looks gorgeous. It's just that a border is missing

**Comment by cristianovitorino** [comment]
@jaames I gave this a try, but I saw no solution, at least for now, other than alter the hue of the exagon a bit and give it a lighter border with a circular radial inside for better contrast. Here's what I came up with:
- **Left:** jaames original design on a very dark background.
- **Center:** My proposal on the same very dark background.
- **Right:** My proposal on a lighter background.

![Solution Proposal](https://user-images.githubusercontent.com/57003922/77461530-77035e00-6de1-11ea-88e3-49e97451700a.png)

[Logo contrast problem proposal.zip](https://github.com/glimpse-editor/Glimpse/files/4376980/Logo.contrast.problem.proposal.zip)

**Comment by TrechNex** [comment]
If you do decide to go for it, I'll need an SVG version to make icons from before the end of this week if you want it in 0.1.4.

I think it would be great to fix this problem right before Ubuntu releases its latest LTS, and we can fix our website so we use the dark background logo instead of the inverted one.

**Comment by cristianovitorino** [comment]
> If you do decide to go for it, I'll need an SVG version to make icons from before the end of this week if you want it in 0.1.4.

It's provided on the link on the bottom. Do you need the logo alone specifically without the background? I can provide that alone in a heart bit.

Should we wait for @jaames feedback or are you ready to greenlit the proposal?

**Comment by TrechNex** [comment]
Correct, I would need it minus the background. Not only would I be using the SVG directly, but I also need to generate PNG images of specific sizes.

I'll give @jaames a few days to look over it. If we don't hear anything I'll greenlight it, but will run it past other governance team members first.

**Comment by TrechNex** [comment]
If you need help on how we did it last time, we actually have a branding repo that this also needs to go int @cristianovitorino https://github.com/glimpse-editor/branding

**Comment by cristianovitorino** [comment]
> If you need help on how we did it last time, we actually have a branding repo that this also needs to go into @cristianovitorino https://github.com/glimpse-editor/branding

Gotcha! Feel free to assign this issue to me if you want and move it on the Kanban board. I can do the heavy lifting of the link, but it takes time and effort so I rather wait for governance to approve first. Let me know of the decision and if jaames is OK with it and have feedback to offer.

Here's the SVG of the logo alone;
[Glimpse Logo.zip](https://github.com/glimpse-editor/Glimpse/files/4377029/Glimpse.Logo.zip)

**Comment by cristianovitorino** [comment]
And if aproved, gimme a few extra hours so I can do some quality of live improvements before doing the size variation and preparing the PR. Very small things, like raising the radial by some small percentage and finding a sweet spot. I went through 7 iterations to get to the current result, but it could benefit from final tweaks and revision to avoid any problems when it goes into production.

**Comment by Feichtmeier** [comment]
> @jaames I gave this a try, but I saw no solution, at least for now, other than alter the hue of the exagon a bit and give it a lighter border with a circular radial inside for better contrast. Here's what I came up with:
> 
>     * **Left:** jaames original design on a very dark background.
> 
>     * **Center:** My proposal on the same very dark background.
> 
>     * **Right:** My proposal on a lighter background.
> 
> 
> _Open the image on another tab for full, detailed resolution. Source SVGs and PNGs included below_
> 
> ![Solution Proposal](https://user-images.githubusercontent.com/57003922/77461530-77035e00-6de1-11ea-88e3-49e97451700a.png)
> 
> [Logo contrast problem proposal.zip](https://github.com/glimpse-editor/Glimpse/files/4376980/Logo.contrast.problem.proposal.zip)

The one in the middle looks fine for me.
Alternatively you could add a "1px" stroke outline to the existing logo with something like ```#3d3d3d```

**Comment by cristianovitorino** [comment]
> The one in the middle looks fine for me.
Left is the original from jaames. Center and right is my solution, they're the exact same logo but in different backgrounds, demonstrating that it works on darker and lighter backgrounds.

> Alternatively you could add a "1px" stroke outline to the existing logo with something like `#cccccc`

Tried that, looks horrible :joy: Plus any outlining should preferably inherit from the established palette. And the current logo palette doesn't give room for neutrals in order to work with all kinds of backgrounds.

I went through 7 iterations, what you see is the best I could came up with at the moment.

**Comment by TrechNex** [comment]
You could try doing it as a semi-transparent diffuse around the logo itself? That way the original colour palette could be preserved.

Although tbh I don't dislike the idea that's already been presented here. :)

**Comment by cristianovitorino** [comment]
> You could try doing it as a semi-transparent diffuse around the logo itself? That way the original colour palette could be preserved.
> 
> Although tbh I don't dislike the idea that's already been presented here. :)

Already tried that. Looks like s**t :joy: 

But that's not my call to make. Gimme a few minutes, I'll post the iterations. Judge for yourselves.

**Comment by cristianovitorino** [comment]
Here. It's important to open them both on new tabs to compare visibility on different scales. A logo should look good on small and large scale. The diffusing suggested by @TrechNex is not that terrible, but it's so cheap and bland. But again, not my choice to make. 
 
**Big scale**
![proposal-full-scale](https://user-images.githubusercontent.com/57003922/77476951-601d3580-6dfa-11ea-80bf-56cecb909fab.png)

**Small scale**
![proposal-scaled-down](https://user-images.githubusercontent.com/57003922/77476975-69a69d80-6dfa-11ea-9d36-fa5b81abd230.png)

**Comment by TrechNex** [comment]
I'm concerned that the colours look slightly off in all of them if you compare to what's on the website & in peoples' app launchers already. Did you use the SVG files provided in the branding repo linked above and use the color codes in the `README.MD` there?

**Comment by jaames** [comment]
Hey! Sorry for not responding sooner, I got a bit sidetracked with the whole covid-19 thing that's been going on. ':)

My initial reaction is that I'm not really sold on changing the background color to a slightly lighter grey. It feels like there would still be contrast issues, just against slightly lighter colors instead.

Honestly rather than having another variant of the logo maybe the solution is as simple as wrapping the icon in a thick-ish white border, like a sticker?

<img width="359" alt="Screenshot 2020-03-24 at 20 54 17" src="https://user-images.githubusercontent.com/9112876/77476384-66b7a700-6e12-11ea-85b4-d5ec82abd180.png">

We could of course try adding some shading to the background too, but personally I prefer not to have lots of different logo variants since it muddies branding a bit.

(PS, @cristianovitorino you might wanna check your color profile settings, those colors seem a bit washed out compared to what's in the branding repo!)

**Comment by cristianovitorino** [comment]
> I'm concerned that the colours look slightly off in all of them if you compare to what's on the website & in peoples' app launchers already. Did you use the SVG files provided in the branding repo linked above and use the color codes in the `README.MD` there?

That's the idea, the hexagon BG is a strong dark blue nearing the absolute black on the shade spectrum, that's why this issue was opened, it doesn't work in dark hued BGs or black BGs. You need to move it up in the shading spectrum so it's not confused with a dark or black background.

I've used the SVG yes, not the color palette. As my worry was with keeping the max of the style of the current logo and make it work on darker and lighter backgrounds.

But I can play around with the README.md and a website screenshot. But I may only be able to do that tomorrow. If I can I'll give it a shot today, not garanteed.

**Comment by cristianovitorino** [comment]
> Honestly rather than having another variant of the logo maybe the solution is as simple as wrapping the icon in a thick-ish white border, like a sticker?

I thought about that, but it would change the logo personality and I didn't want to disrespect your design.

**Comment by TrechNex** [comment]
tbh I'm fine with the white sticker-like border. Although that could be my aversion to change talking. We've had a lot of positive feedback around the current logo

**Comment by cristianovitorino** [comment]
> We could of course try adding some shading to the background too, but personally I prefer not to have lots of different logo variants since it muddies branding a bit.

These are proposals side by side (one in a dark BG, one in a light BG), not variants, in case you're talking about my images, sorry and ignore if I'm mistaken.

> (PS, @cristianovitorino you might wanna check your color profile settings, those colors seem a bit washed out compared to what's in the branding repo!)

Not at all, my monitor is well calibrated and ready for color work. It's intentional. As I said in the previous comment (take a second look at that, I think we posted almost at the same time) the original hexagon is deep dark bluel, there is no easy scape from that other than "hue it up" a notch so it can work in dark and lighter BGs. Or, change the logo personality and throw a white outline like you did, I didn't want to do that, looks like a sticker like you said. But if that's the direction everybody wants I'm cool with that, looks good.

**Comment by TrechNex** [comment]
Coolio. @jaames would you be able to get some new SVGs in the branding repo some time this week? If so I can add this change in 0.1.4 and it'll roll out across all our Linux/Windows builds for that release after I've updated all the relevant icon packs, etc

**Comment by TrechNex** [comment]
If not, don't worry as I can push it out to 0.1.6 (due in May) instead.

**Comment by cristianovitorino** [comment]
@TrechNex If that's the final decision feel free to unassign me, leave the path open for jaames.

**Comment by TrechNex** [comment]
No worries. Thanks for helping us with this @cristianovitorino, we will still need your design expertise with other icon fixes through the application.

#282 for example needs variations on this logo for preview icons and it looks like you're well placed to have a crack at that. :)

**Comment by cristianovitorino** [comment]
> No worries. Thanks for helping us with this @cristianovitorino, we will still need your design expertise with other icon fixes through the application.

My pleasure : )

> #282 for example needs variations on this logo for preview icons and it looks like you're well placed to have a crack at that. :)

Shouldn't we focus on #285 instead? As you mentioned on #282.

If jaames is not gonna work on that, I would like to tackled that yeah.

**Comment by TrechNex** [comment]
Closing as work on this is complete.

**Comment by Feichtmeier** [comment]
Nice, thank you very much @TrechNex

**Comment by TrechNex** [comment]
Reopening issue after discussion on Matrix. cc @cristianovitorino and @jaames 
The sticker border solution is sufficient, but we can probably do better :)

**Comment by cristianovitorino** [comment]
The main problem with the sticker-like thin white border solution is that it's thin, and well, looks like a sticker. The real problem appeared after it was implemented project wide, website, etc, the thin white border looks aliased (stairway effect) on small resolutions, even on 1440p screens when the logo is scaled to a smaller size. The "sticker" style is more of a aesthetic thing, and not a priority per se, but the visibility of the logo on small scales and small resolutions is a real problem.

**Comment by cristianovitorino** [comment]
@jaames Help me here buddy.

**Comment by cristianovitorino** [comment]
Let's start the iteration process again shall we? How about this:

![iteration](https://user-images.githubusercontent.com/57003922/82134523-50551880-97cf-11ea-93f6-44d377f03ad1.png)

**Comment by Member1221** [comment]
imo, the colors on that are very cold, what if it was made a bit more vibrant/warm?

**Comment by cristianovitorino** [comment]
> imo, the colors on that are very cold, what if it was made a bit more vibrant/warm?

What do you mean?

1. The whole logo.
2. The border.
3. The inner lenses elements.

**Comment by Member1221** [comment]
I guess I meant the color warmth? Some of these terms is a bit confusing to me. But like, the color of the log from before looks really cold and lifeless compared to if it got some warmth added to it. Vibrancy just made the cold colors stand out more

**Comment by cristianovitorino** [comment]
> I guess I meant the color warmth? Some of these terms is a bit confusing to me. But like, the color of the log from before looks really cold and lifeless compared to if it got some warmth added to it. Vibrancy just made the cold colors stand out more

"Cold" and "Warm" are commonly OK terms to use, so is "Dark" and "Bright", just make sure you know what you're referring to. 

What I understood from your statement previously is that you wanted more hue saturation. And that's what I did on my previous attempt.

![brighter](https://user-images.githubusercontent.com/57003922/82162257-6ae3cc00-9879-11ea-9cdc-c825755a74a5.png)
![lighter](https://user-images.githubusercontent.com/57003922/82162260-720ada00-9879-11ea-9fde-c02244df41c7.png)
![darker](https://user-images.githubusercontent.com/57003922/82162261-759e6100-9879-11ea-85e5-151c71520f6a.png)

- Hue values in HSL goes from 0 to 360, or from red to red on a full color spectrum.
- Saturation values goes from 0 to 100.
- Light values goes from 0 to 100.

#### These are some common conventions that you can use to play around with Color Theory:
- For brightness: Keep Saturation around 100 and Light around 50.
- For lighter/pastel: Keep Saturation below 50 and Light above 50.
- For darker/shadows: Keep Saturation above 50 and Light below 50.
- For neutrals: Keep both Saturation and Light at 50.
- "Warmth" is quite subjective, IMO it would be something like (let's say, red):
    - H: 0
    - S: ~50-75 - Intensity of the warmth - Above 75 is "Hot" or "Bright" territory for me.
    - L: 50

---

I'll do a "warm" version and compare it side by side with the "bright" one above.

_**P.S.:** Black and White are not colors, they don't have hues, they're either the presence or absence of light._

_**P.S.2:** For full work on the rewrite I'll need to wait for my PC parts to arrive, so I can at least help here while I wait. I just can't do complex things as Figma starts to freeze on me on this ancient Mac LOL A single logo is fine._

**Comment by cristianovitorino** [comment]
More iterations. The first one is a mockup from @jaames (that he used for other purposes) that I'm using as inspiration.

![93hdf](https://user-images.githubusercontent.com/57003922/82735560-0604f780-9cf9-11ea-8d95-1b5b880b3c8d.png)

![sj68](https://user-images.githubusercontent.com/57003922/82735564-09987e80-9cf9-11ea-99b1-e49fcd72665a.png)

**Comment by jaames** [comment]
> #### Another iteration from me
> ![sj68](https://user-images.githubusercontent.com/57003922/82735564-09987e80-9cf9-11ea-99b1-e49fcd72665a.png)

The blue and orange ones here look *super* hot, but not sure about readability which is a shame

> #### Scaling problem proposed solution
> ![sdfijsa54](https://user-images.githubusercontent.com/57003922/82735920-d2779c80-9cfb-11ea-9a1d-300cef7c3ce7.png)

The white outline reads better to me here

Also, I think if we're going to fix the outline, where possible it would be a good idea to make sure it's pixel-hinted for the sizes the icon is going to be rendered at

**Comment by cristianovitorino** [comment]
> The blue and orange ones here look _super_ hot, but not sure about readability which is a shame

Yeah I noticed, just throwing things at the wall, see what sticks, what works, what doesn't.

> The white outline reads better to me here
> Also, I think if we're going to fix the outline, where possible it would be a good idea to make sure it's pixel-hinted for the sizes the icon is going to be rendered at

Yup.

**Comment by cristianovitorino** [comment]
OK *panting after running from Color Theory demons* here's another round of ideas:

- Top row **LEFT** has 10 | 30 | 100 % transparency, front to back.
- Top row **RIGHT** has 10 | 30 | 100 % transparency, front to back + no particles.
- Bottom row **LEFT**: Color median.
- Bottom row **RIGHT**: No particles, plain tiles + color median.

![sdfg894t](https://user-images.githubusercontent.com/57003922/82753863-9433b900-9d9f-11ea-89ae-b85e1fd4270f.png)

**Comment by TrechNex** [comment]
@estatra Could you raise a new issue with your design suggestions please? For 0.2.0 I believe we'll be going with the "sticker" logo, but the concepts you came up with here could be used in a future release (for example, 0.3.0) :)

That would then allow me to close this issue as done.

**Comment by estatra** [comment]
@TrechNex Done. [#413](https://github.com/glimpse-editor/Glimpse/issues/413)
