### ISSUE TITLE
State of Libre Graphics 2020

### ISSUE THREAD

**Issue by aoloe** [glimpse-editor/Glimpse#324]
The [Libre Graphics Meeting 2020](https://libregraphicsmeeting.org/2020/) is happening at the end of May in Rennes!

As usual, the first conference will be the State of Libre Graphics, where we will give an overview of what has happened during the last year in the world of Libre Graphics.

You're very welcome to submit two slides for your project. They will be presented by the moderator of the _State of Libre Graphics_.
Instructions for submitting the slides can be found in the Github repository that will contain all slides:

<https://github.com/libregraphicsmeeting/state-of-lg-2020>

If you have further questions, don't hesitate to [open a ticket](https://github.com/libregraphicsmeeting/state-of-lg-2020/issues) in the same repository.

And, of course, you're very welcome to [join us in Rennes](https://libregraphicsmeeting.org/2020/en/register.html)!

**Comment by TrechNex** [comment]
Thank you for reaching out to us. I've tagged this to our 0.2.0 release as the timeline for that work and these slides is similar.

**Comment by aoloe** [comment]
thanks!

**Comment by TrechNex** [comment]
Closing as there is no Libre Graphic Meetup 2020.
