### ISSUE TITLE
Add donate link to Help menu

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#333]
### Is your feature request related to a problem? Please describe
Many projects provide donate links within the UI to encourage people to contribute towards the running costs of that project. We should look into ways of doing this too.

### Describe the solution you'd like
A link in the help menu or About window.

### Describe alternatives you've considered
Relying on people finding it themselves through social media and our blog.

### Additional context
We should take care to ensure it's crystal clear to users that it's a donate link for our project and not upstream so we are not open to spurious accusations. 

Similarly, we should ensure that we continue to make it clear in the GUI that our work is based on the GNU Image Manipulation Program (and link back to it) so we can keep acting as a "stepping stone" to that project.

We will also need to reassure the community that our software will continue to be offered at zero cost and under the same GNU GPLv3 license terms in case anyone gets spooked by this.

**Comment by ab1nash** [comment]
@TrechNex I want to give this a go

**Comment by TrechNex** [comment]
Closing as the feedback we've had about this on social media has been generally negative.
