### ISSUE TITLE
New system installed fonts are not present

### ISSUE THREAD

**Issue by dvisan** [glimpse-editor/Glimpse#348]
### Describe the bug
Several Google fonts were installed in the system via Typecacther, after Glipmse was installed via Snapd. The fonts appear in other apps and can be used. Glimpse does not show the fonts in the Font Menu. Using the option 'Rescan Font List' is not working either.

### Desktop (please complete the following information)
 - OS: elementary OS
 - Version 5.1.2 Hera

**Comment by TrechNex** [comment]
cc @hellsworth as she is maintaining the Snapcraft packaging.

If there is no quick fix then next week there will be a new release (0.1.4) that fixes the problems you might have experienced with the Flatpak on elementaryOS.

**Comment by dvisan** [comment]
The problem I was experiencing was for a Glimpse version installed via Snapcraft, as mentioned in the issue.
Now I have removed the snap for Glimpse and reinstalled the app via Flatpak. I can confirm the issue is exhibiting in the Flatpak version too. Currently there is not other way to install Glimpse on a Debian-based system. I will wait for v.0.1.4.

Thanks again for the fast responses!

**Comment by TrechNex** [comment]
You're welcome :) 

We will need to check if this is a problem in other Linux distributions too, as if it's an issue with the Flatpak too it could be related to how the packaging formats are "containerized".

There are also plans to do a self-updating AppImage as well, and presumably that would need to pick up system fonts too.

Imho the solution will probably be either to change the packaging processes, or to document what users have to do in config.

**Comment by TrechNex** [comment]
In the meantime btw you could try Edit > Preferences > Folders > Fonts.

**Comment by dvisan** [comment]
Thank you for the work-around.
I've opened the Font Folders options and the only two paths present are for Glimpse font folders, with one being empty and the other non-existent.

The **fonts.conf** file present at `/etc/fonts/fonts.conf` lists the following sources for fonts:

```
<!-- Font directory list -->

	<dir>/usr/share/fonts</dir>
	<dir>/usr/local/share/fonts</dir>
	<dir prefix="xdg">fonts</dir>
	<!-- the following element will be removed in the future -->
	<dir>~/.fonts</dir>

<!--
```
And the file also ends with the following block:

```
<!--
  Rescan configuration every 30 seconds when FcFontSetList is called
 -->
		<rescan>
			<int>30</int>
		</rescan>
	</config>

</fontconfig>
```
At least on elementary.

Thanks for responding so fast!
