### ISSUE TITLE
Don't do pointless work

### ISSUE THREAD

**Issue by CameronNemo** [glimpse-editor/Glimpse#35]
The Free Software community has a lot of work cut out for ourselves. Not only are we competing with proprietary platforms like Windows and iOS, but we also need to defend against attacks from within the community by organizations like Google who push users toward proprietary web services.

Forking GIMP (pronounced "gee-imp") offers little in the way of improving free software's competitive advantage.

Please consider searching for a more productive use of your time, for the sake of your own sense of fulfillment as well as the success of the free software community as a whole.

Regards,
Cameron Nemo

**Comment by Member1221** [comment]
We do not find this work to be pointless. If you do not like our work feel free to continue using the upstream GNU Image Manipulation Program.

**Comment by CameronNemo** [comment]
I am not opposed to the effort, I just think a hard fork is incredibly inefficient. I hope you reconsider that aspect and instead contribute patches upstream to make renaming/rebranding a simple compile time option.

**Comment by Member1221** [comment]
We're working on restructuring a lot of this project to make it easier to maintain, some changes will not be compatible with upstream GNU Image Manipulation Program, as well there's a bunch of things we do want to do different than GIMP at some point.

If they want our changes they're free to take them in. But we have very different viewpoints on how a project like this should be handled.

**Comment by joshgiesbrecht** [comment]
If there was a reasonable indication that upstream maintainers would take such a patch, it *might* be worth the time.

As it stands now, based on their responses, I would think that coding a compile time option for a rename (or any other upstream-aimed fix) would be the bigger waste of time.

⁣Sent from Blue ​

**Comment by BrainBlasted** [comment]
Yes. Upstream has already indicated that they have a hard-line stance on not changing the name, including via build options.

**Comment by prokoudine** [comment]
> there's a bunch of things we do want to do different than GNU Image Manipulation Program at some point

Which you did not discuss with the upstream project though. So how exactly do you know the upstream project is against doing "a bunch of things" differently?

**Comment by Member1221** [comment]
Mostly stuff they've been against in the past; like looking at the UX and giving it an overhaul when able, as well the project managment will not be BDFL.

**Comment by TreacherousNexus** [comment]
Questions like this have been answered in https://getglimpse.app/about/
