### ISSUE TITLE
Free Software image manipulation package callled Glimpse already exists

### ISSUE THREAD

**Issue by frumiousbandersnatch** [glimpse-editor/Glimpse#354]
https://sourceforge.net/projects/glimpse-soft/

**Comment by TrechNex** [comment]
This is a project we're aware of, but thank you for informing us.  :)

Our understanding is that contrary to the "last updated in 2015" claim on Sourceforge, the code was actually abandoned 16 years ago and never got past the early development stage. It does not have a userbase, is not in any Linux repositories, and it's doubtful we'll be duking it out with them in the search engine rankings any time soon.
