### ISSUE TITLE
How do I find the community forum?

### ISSUE THREAD

**Issue by SB2020-eye** [glimpse-editor/Glimpse#366]
Hi. I was looking for the community forum, to do some searching...before posting somewhere! (Irony)

I did see at [](https://glimpse-editor.org/about/) that "All of our channels are on matrix.org." And that "#glimpse" is the “'Glimpse Community' channel that anyone can join." But - please bear with me - I couldn't figure out how to find any channels on matrix.org.

Can someone help point me there? (Or is this here, on github, the best space at present?)

Meanwhile, what I'm trying to find out is if the following are part of Glimpse:
1. Any kind of content-aware fill
2. Any kind of automated object/subject select
3. Any kind of selecting (or limiting or adding to selections) based on size - eg, I use the fuzzy select tool, but want it to select only areas larger than 20 pixels in diameter (or something like that)
(And if that isn't already a feature, if that might be possible with a script)

Thank you for answering any or all of these qs. All the best!

**Comment by TrechNex** [comment]
If you click on the Matrix link here it will provide instructions for how to install compatible client software and how to connect to the channel: https://glimpse-editor.org/contribute/

Your best bet with those three feature requests would be to check if there has been a Github Issue already raised for them. If not, create one! We can then categorize and prioritize it. https://glimpse-editor.org/about/#when-are-you-going-to-implement-the-feature-i-asked-for

I also recommend taking a look over our FAQs page as you might find some answers to further questions too. :)

https://glimpse-editor.org/about/
