### ISSUE TITLE
Update splash screen for Glimpse Image Editor 0.1.4

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#370]
We have updated the logo to the new sticker one, so we need to do this anyway.

My suggestion is to keep it similar, but use a modified version of the "unsplash" flowers image we use on the website. They're a similar colour to the current "blurry landscape" image we use, so it makes sense.

**Comment by TrechNex** [comment]
More radical ideas should be saved for #304

**Comment by cristianovitorino** [comment]
@TrechNex @jaames Here are my takes.

![glimpse-splash-screen-pink-flowers](https://user-images.githubusercontent.com/57003922/78958012-4d268880-7abd-11ea-9b35-a0f8dfaa76ba.png)

![glimpse-splash-screen-yellow-flowers](https://user-images.githubusercontent.com/57003922/78958033-59124a80-7abd-11ea-9e69-73d2476bbb82.png)

**Comment by cristianovitorino** [comment]
@TrechNex Is this sufficient? Do you want more iterations? Need something else?

**Comment by TrechNex** [comment]
The first one looks good to me. If you could commit it to the branding repo, that'd be much appreciated.

I will subsequently crop it for use in banners for our various social media & fundraising pages.

**Comment by cristianovitorino** [comment]
Cool. [Done!](https://github.com/glimpse-editor/branding/pull/8)
