### ISSUE TITLE
Add custom install location option in Windows installer

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#371]
### Is your feature request related to a problem? Please describe
Currently the MSI is entirely silent, and does not offer the user an option to use custom install location.

### Describe the solution you'd like
We should pop up an optional dialogue that enables people to set a custom install location.

### Describe alternatives you've considered
Just waiting until an MSIX is produced, when this would be irrelevant except for backwards-compatibility.

### Additional context
This is a feature we see requested a lot on social media.

**Comment by Member1221** [comment]
On top of that it should probably show the license terms of the application which you have to agree to as well.

**Comment by TrechNex** [comment]
Also adding note to remove unneeded Python 2 dependencies and plug-ins.

Python 2 is end of life and we're not using those things anyway, so might as well save some disk space/download bandwidth. :)

**Comment by TrechNex** [comment]
This was fixed in #434
