### ISSUE TITLE
Seriously why don't you just make a patch file and release it?

### ISSUE THREAD

**Issue by discapes** [glimpse-editor/Glimpse#38]
Also, why would you need Patreon support just for your little effort to change a programs name?

**Comment by joshgiesbrecht** [comment]
Is this an honest good-faith question, or can I just dismiss this as trolling and block you?

**Comment by adrianmalacoda** [comment]
You are indeed correct that they don't need a Patreon just to change the name of something. That is why it is fortunate [that's not all they're planning to do](https://bobadon.co.uk/@glimpse/102400738093815123).

**Comment by dginovker** [comment]
You sure about that? I'm not an expert but it looks like they tried to do something like that https://github.com/glimpse-editor/Glimpse/commit/84ec78d4ff017da83703b2831c35ebd5f21a0820

**Comment by Member1221** [comment]
Initial release (1.0) will be a simple rebranding. After which the hard fork will commence in which we plan to introduce new features and UI improvements.

**Comment by TreacherousNexus** [comment]
Answers to questions like this are answered in https://getglimpse.app/about/
