### ISSUE TITLE
Any interest in contributors for a better Glimpse website?

### ISSUE THREAD

**Issue by joniler** [glimpse-editor/Glimpse#387]
I feel that the new website isn't a great representation of the new direction of the project. The website should be updated to look good and give people a good impression of the new redesign and etc.

Are you guys interested in contributors for that? I am a frontend web developer and would be interested in contributing to that.

I couldn't find anywhere else to send this/post this, so I figured an issue on Github was the best way to go.

Cheers!

**Comment by TrechNex** [comment]
The current code for it is here: https://github.com/glimpse-editor/getglimpse-web

Assigning to @BrainBlasted as he is in charge of the website's design. I mostly just add content to it. :)

**Comment by joniler** [comment]
@TrechNex awesome! I'll head over to that repo and get in touch with @BrainBlasted. Excited to potentially work with you guys! :)
