### ISSUE TITLE
please improve the ui

### ISSUE THREAD

**Issue by mobop** [glimpse-editor/Glimpse#388]
the and feel of the ui of gimp sucks. you must give it a modern look.

**Comment by TrechNex** [comment]
Thank you for your support. If you want to keep track of what we're up to, we now have a product board where you can see planned changes: https://github.com/glimpse-editor/Glimpse/projects/1

Credit where it's due, the GNU Image Manipulation Program have made some changes in recent releases (we will eventually rebase on them) and they have apparently been working on a GTK3 port for some time.

We intend to explore some interesting new ideas for Glimpse Image Editor in future releases. 0.2.0 for example will likely include new UI themes and icon packs to make things looks more modern, and we have designers working on those now :)
