### ISSUE TITLE
Is the name unique enough?

### ISSUE THREAD

**Issue by lorendias** [glimpse-editor/Glimpse#39]
1. Is the name uniquely identifiable?
2. Is it distinguishable from other products, services, and domain names
3. Will search engine results yield relevant information, for competition see Google Tends
https://trends.google.com/trends/explore?geo=US&q=glimpse,gimp
4. Are the twitter accounts, subreddits, Facebook page names and domain names available?
Based on the github name I imagine the domain would look like this:
www.glimpseeditor.com
www.glimpseeditor.com

However it generally frowned upon to have the last letter and first letter of each word be the same.

If the name is not finalized but merely a "dev codename", I suggest taking these branding needs into consideration. Out the gate the name is a massive improvement over the existing.

**Comment by BrainBlasted** [comment]
The plan is to market as something like "Glimpse Photo Editor". We are also using the domain getglimpse.app.

**Comment by Member1221** [comment]
The search engine result stuff is mainly about doing SEO. Which would be an issue for https://github.com/glimpse-editor/getglimpse-web :)

**Comment by TreacherousNexus** [comment]
The domain we've gone with so far is getglimpse.app. Although if you go there at the moment you just see an empty Hugo site because we've not added content or deviated from the stock theme yet!

**Comment by TreacherousNexus** [comment]
I'm also quite partial to "Glimpse Image Editor". That probably ties in more nicely to our social media handles than "Image Manipulator", but I've put that as placeholder text at the IRC channel's request.

**Comment by Member1221** [comment]
more specifically my request XD
But yeah Image Editor could be fine as well.

**Comment by TrechNex** [comment]
This has been answered in the FAQs here: https://getglimpse.app/about/#did-you-know-that-name-is-used-elsewhere

**Comment by TrechNex** [comment]
Linking to #92
