### ISSUE TITLE
A way to organize fonts in the fonts dialog

### ISSUE THREAD

**Issue by nullbasis** [glimpse-editor/Glimpse#391]
One of the issues I've had for many years in GNUIMP is the way all the fonts I have are just there in one big list. It's unwieldy and frustrating to sort through.

A way to organize fonts would be great. The solution I'm envisioning is user-definable tags, so users could see all their pixel fonts at once, or all their script fonts, or all their fonts with a specific GPL license... etc.

(I got here by clicking Feature Request, but I can't find a way to apply the Enhancement label, sorry. I'm not good at Github.)

**Comment by Member1221** [comment]
Don't worry, labels can only be applied by maintainers.
Thanks for the feature request :)

Will set the milestone for hard fork for now.

**Comment by TrechNex** [comment]
Moved to "Fork Candidates". 1.0.x Candidates implies we'll get it done when we re-fork from upstream v3.0, but we may be able to do it sooner.

**Comment by prokoudine** [comment]
Fonts can be tagged in the _Fonts_ dockable dialog since GIMP v2.10.4.

**Comment by TrechNex** [comment]
It sounds like this may just be a case of learning about dockable dialogs in that case. :)

@nullbasis I've found the YouTube videos by Davies Media Design quite useful recently, so you might want to give those a whirl: https://www.youtube.com/channel/UCq79-lfj2w7oRXGRcOP2B7g

**Comment by nullbasis** [comment]
Oh, wow, I had no idea about this. Thanks!
