### ISSUE TITLE
glimpse-editor.org is down?

### ISSUE THREAD

**Issue by d1moncom** [glimpse-editor/Glimpse#395]
Network is unreachable
HTTP response timed out
etc...
https://www.host-tracker.com/v3/check/3/0fe6b81f-5c44-4d72-b712-d6776c2de420

**Comment by TrechNex** [comment]
Well spotted. About 9 hours ago Linode had to perform emergency maintenance on the host the VPS we're running the website from is on.

Something seems to have gone wrong with the box since then. cc @chaomodus in case they have any ideas, but they're on a US timezone.

**Comment by TrechNex** [comment]
Attempting to restore the VPS from a known good backup from last week. With any luck that will do the trick!

**Comment by TrechNex** [comment]
Nope, that didn't work. I've responded to the ticket the host has raised about the issue to point out they've basically just borked our VPS in the hope they have some kind of backup.

If they don't, we'll come up with a solution this evening (BST)

**Comment by sir-ragna** [comment]
I'm not sure whether it is worth setting up a 'temporary down'-page? I imagine not everyone will come looking on Github for the reason of the outage.

In any case, the best of luck with the restoration of the VPS!

**Comment by TrechNex** [comment]
Thank you. The main problem is it's Monday, and I still have a day job. If I can do something during my lunch break today (UK time) I will :)

**Comment by TrechNex** [comment]
We have an update from Linode. From their point of view the VPS is fine, but nothing seems to be listening on ports 80 and 443.

This will have to wait until this evening BST when @chaomodus is back online, as I'm having trouble getting into the VPS to check the logs and verify the status of our web server.

**Comment by TrechNex** [comment]
To update, I've come up with a faster solution.

I have now switched the web hosting to a `docs` subfolder in the getglimpse-app repository we already use to publish our website.

I am waiting on a few other people to test that the https://glimpse-editor.org URL is working fine. If it does, then I will pronounce the problem fixed on social media.

**Comment by sir-ragna** [comment]
Works for me. :+1:

**Comment by TrechNex** [comment]
Awesome! We also had some confirmations on Matrix too so closing this issue as fixed.
