### ISSUE TITLE
How can I install custom theme when using snap package?

### ISSUE THREAD

**Issue by steveunixson** [glimpse-editor/Glimpse#398]
Unable to install theme then Glimpse is installed from snap

I am having a problem installing a custom theme because snap directory is read-only and theme files are located there. 
As far as I know when you install gimp it should create a .gimp2 directory in users home, but I can't see it. I've found out that snap package contains themes at
`/snap/glimpse-editor/current/usr/share/glimpse/2.0/themes`

but I can't copy any files there because snap is usualy mounted as read-only
So what can I do?

**Comment by TrechNex** [comment]
In the Edit > Preferences > Folders panel you can add extra locations for custom themes.

cc @hellsworth as she was looking into this for related issues such as #379

**Comment by hellsworth** [comment]
Right.. where this was left off was that I was able to build and include the newer version of rawtherapee but couldn't get the plugin auto-loaded for some reason. I still need to find some time to work on that last bit.

**Comment by TrechNex** [comment]
No worries. As an FYI @hellsworth I have rebased the code on 2.10.18 and had to make some updates to plug-in/PDB support to make that build. That will probably get merged into dev branch tomorrow evening (UK time)

**Comment by TrechNex** [comment]
Closing as answered
