### ISSUE TITLE
Should we use the keyboard shortcuts from PhotoGIMP?

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#412]
### Is your feature request related to a problem? Please describe
I recently wrote a Wiki page about how to convert Glimpse Image Editor into PhotoGIMP, and we have since had a surprising number of people ask if we could make PhotoGIMP's key bindings the default.

It could be another point of differentiation for our fork, and would be in line with our mandate to reach out to people who do not already use the GNU Image Manipulation Program.

### Describe the solution you'd like
We could switch to those key bindings, but we should check user opinions first. Beta testing would also determine if any keyboard shortcut changes were still needed.

### Describe alternatives you've considered
Leaving the key bindings as-is and just documenting how to change them.

### Additional context
Our wiki guide: https://github.com/glimpse-editor/Glimpse/wiki/How-to-Install-the-PhotoGIMP-Plugin
PhotoGIMP project: https://github.com/Diolinux/PhotoGIMP.git

**Comment by TrechNex** [comment]
I published social media polls for us to watch over the next week or so to gauge likely response to it:
https://mastodon.art/@glimpse/104416012367916372
https://twitter.com/glimpse_editor/status/1276859116607229953?s=20

As per our FAQs the final result won't make the decision for us, but how the polls shift over the course of the week in reaction to weekend crowd vs weekday crowd and any potential response from trolls will be very informative.

I think the comments offering constructive suggestions are already proving useful :)

**Comment by TrechNex** [comment]
Provisionally making a 0.2.x candidate. It's possible that it might have to be kicked out to a later release if we want to prompt the user on first run to accept PhotoGIMP default keybindings or "legacy" GNU Image Manipulation Program keybindings.

My concern with that approach is that users may not know the difference, and because "PhotoShop" is a trademark owned by Adobe we would probably not be allowed to use it in any in-app explanations.

One potential solution is to change the default but then provide documentation for how to revert to the "legacy" key bindings. In a later release we could then provide a plug-in that enables users to switch between different pre-defined key bindings without having to do it manually through the UI or copying config files.

**Comment by TrechNex** [comment]
Another way we could do it is to stick with the current key bindings on Linux, but offer Windows users a choice at install time.
Such a solution could be done in time for the 0.2.0 release. :)

**Comment by jcklpe** [comment]
I've known about glimpse for awhile. As soon as I heard about photogimp today I came to the glimpse github to post about it. I think this is a great idea. Gimp isn't just a bad name, it's in bad need of ui updates. Blender recently overhauled their ui and brought it more in line with industry standard and this was a great idea and I think glimpse could really benefit from a similar shift.

It gives some real practical quality of life improvements over gimp.

**Comment by TrechNex** [comment]
Was added to 0.2.0 release
