### ISSUE TITLE
Using "Open with" on windows fails

### ISSUE THREAD

**Issue by ChildishGiant** [glimpse-editor/Glimpse#416]
I can't use the "Open with" dialog on any images. The same images can be loaded once the app is open.
![image](https://user-images.githubusercontent.com/13716824/86680897-f31f5b80-bff6-11ea-9590-a6daeacd231a.png)

![image](https://user-images.githubusercontent.com/13716824/86680546-96bc3c00-bff6-11ea-95cc-20183ed19302.png)
The code execution cannot proceed because libgimpcolor-2.0-0.dll was not found. Reinstalling the program may fix this problem.

![image](https://user-images.githubusercontent.com/13716824/86680572-9de34a00-bff6-11ea-9c51-7fbd3181284d.png)
The code execution cannot proceed because libgimpconfig-2.0-0.dll was not found. Reinstalling the program may fix this problem.

![image](https://user-images.githubusercontent.com/13716824/86680639-afc4ed00-bff6-11ea-9f30-2263db99def6.png)
The code execution cannot proceed because libgimpmath-2.0-0.dll was not found. Reinstalling the program may fix this problem.

![image](https://user-images.githubusercontent.com/13716824/86680687-ba7f8200-bff6-11ea-9e40-f6c39cfd2aec.png)
The code execution cannot proceed because libgimpmodule-2.0-0.dll was not found. Reinstalling the program may fix this problem.

I've reinstalled and that didn't fix the issue

**Comment by Member1221** [comment]
I suspect it might be something to do with the working directory @TrechNex. 
We might want to modify the shortcut to always use Glimpse's directory as the working directory.

**Comment by TrechNex** [comment]
Also applying the packaging label as it's something I need to set during the install phase. For 0.2.0 I'm working on two new MSI installers, so the fix can be applied at the same time.

**Comment by TrechNex** [comment]
Possibly duplicates #265

**Comment by TrechNex** [comment]
A fix has now been applied and will be available in 0.2.0. We'll be testing it in the beta build this weekend.
