### ISSUE TITLE
erro tool decompor

### ISSUE THREAD

**Issue by PAULOVITOR85** [glimpse-editor/Glimpse#428]
Glimpse version 2.10.18
git-describe: eb09b01fd8
Build: unknown rev 0 for linux
# C compiler #
	Using built-in specs.
	COLLECT_GCC=gcc
	COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
	OFFLOAD_TARGET_NAMES=nvptx-none
	OFFLOAD_TARGET_DEFAULT=1
	Target: x86_64-linux-gnu
	Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
	Thread model: posix
	gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

# Libraries #
using babl version 0.1.78 (compiled against version 0.1.78)
using GEGL version 0.4.22 (compiled against version 0.4.22)
using GLib version 2.56.4 (compiled against version 2.56.4)
using GdkPixbuf version 2.36.11 (compiled against version 2.36.11)
using GTK+ version 2.24.32 (compiled against version 2.24.32)
using Pango version 1.40.14 (compiled against version 1.40.14)
using Fontconfig version 2.12.6 (compiled against version 2.12.6)
using Cairo version 1.15.10 (compiled against version 1.15.10)

```
> Glimpse-CRITICAL: gimp_display_shell_flush: assertion 'GIMP_IS_DISPLAY_SHELL (shell)' failed

Stack trace:
```
/snap/glimpse-editor/140/usr/lib/libglimpsebase-2.0.so.0(gimp_stack_trace_print+0x326) [0x7f6827a989b6]
/snap/glimpse-editor/140/usr/bin/glimpse(gui_message+0x2b9) [0x56443bf11929]
/snap/glimpse-editor/140/usr/bin/glimpse(gimp_show_message+0xfb) [0x56443c1e345b]
/snap/glimpse-editor/140/usr/bin/glimpse(+0xdd03a) [0x56443bf0703a]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_logv+0x251) [0x7f6824bff1c1]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_log+0x8e) [0x7f6824bff31e]
/snap/glimpse-editor/140/usr/bin/glimpse(+0x1c89f1) [0x56443bff29f1]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x19c) [0x7f6824ed310c]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2305d) [0x7f6824ee605d]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xa74) [0x7f6824eee714]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8e) [0x7f6824eef12e]
/snap/glimpse-editor/140/usr/bin/glimpse(gimp_display_shell_set_show_all+0x7f) [0x56443bff6f3f]
/snap/glimpse-editor/140/usr/bin/glimpse(+0x1cdf36) [0x56443bff7f36]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x158ff) [0x7f6824ed88ff]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_new_valist+0x3cf) [0x7f6824eda5bf]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_new+0x98) [0x7f6824eda938]
/snap/glimpse-editor/140/usr/bin/glimpse(gimp_display_shell_new+0x150) [0x56443bff53b0]
/snap/glimpse-editor/140/usr/bin/glimpse(gimp_display_new+0x1db) [0x56443bff339b]
/snap/glimpse-editor/140/usr/bin/glimpse(+0xe2308) [0x56443bf0c308]
/snap/glimpse-editor/140/usr/bin/glimpse(+0x31e9ac) [0x56443c1489ac]
/snap/glimpse-editor/140/usr/bin/glimpse(gimp_procedure_execute+0x218) [0x56443c1b50d8]
/snap/glimpse-editor/140/usr/bin/glimpse(gimp_pdb_execute_procedure_by_name_args+0x1e0) [0x56443c1ae580]
/snap/glimpse-editor/140/usr/bin/glimpse(gimp_plug_in_handle_message+0x23a) [0x56443c1b91ba]
/snap/glimpse-editor/140/usr/bin/glimpse(+0x38dada) [0x56443c1b7ada]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x154) [0x7f6824bf8284]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c64f) [0x7f6824bf864f]
/snap/glimpse-editor/140/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0xc1) [0x7f6824bf8961]
/snap/glimpse-editor/140/usr/bin/glimpse(app_run+0x35a) [0x56443bf06bca]
/snap/glimpse-editor/140/usr/bin/glimpse(main+0x37b) [0x56443bf0648b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe6) [0x7f6823e00b96]
/snap/glimpse-editor/140/usr/bin/glimpse(_start+0x29) [0x56443bf06629]

```

**Comment by TrechNex** [comment]
Linking to #415. Not explanation has so far been given by OP about what they're doing and how they're trying to accomplish it.

There is extensive build documentation provided here for your convenience: https://github.com/glimpse-editor/Glimpse/wiki

**Comment by TrechNex** [comment]
This user has ignored repeated attempts to provide more information about what they're doing so we can troubleshoot this issue. Closing as wontfix
