### ISSUE TITLE
Create a Narrator plug-in

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#438]
### Is your feature request related to a problem? Please describe
People with learning difficulties and dyslexia often use comprehension software that narrates the word (or function in the case of icons) that they have just clicked on. We could provide similar "out of the box" functionality.

### Describe the solution you'd like
The plug-in would (when enabled) use a speech synthesizer to read out the necessary text. I could be triggered via a menu item and/or a keyboard shortcut.

The additional benefit is that such a plug-in would be portable to upstream GNU Image Manipulation Program.

### Describe alternatives you've considered
We could also verify that existing comprehension software works, and make tweaks to the UI code as needed.

**Comment by BrainBlasted** [comment]
This is going to be a hard one to handle; GTK3+ is compatible with existing desktop screenreaders. GTK4 will also have a much better accessibility system. GTK2, however, does not seem to work with existing screen reader software, which means we'll have to bake in our own from scratch.

**Comment by BrainBlasted** [comment]
If this is mainly targeted toward Glimpse NX, I don't think we'll need to do it ourselves.

**Comment by TrechNex** [comment]
This was an idea I came up with before we changed what we were doing with the rewrite. So I have no objections to closing it.
