### ISSUE TITLE
Create a "de-gimpify" optional build flag for translation files

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#447]
### Is your feature request related to a problem? Please describe
The most time-consuming part of our releases (now that we have automated most of our builds and packaging) is fixing up the translation files.

In principle we can automate changing the word "GIMP" to "GNU I.M.P". The tricky part is having to use human intervention to determine when we are referring to our software (Glimpse) and upstream specifically (GNU I.M.P)

I don't think there is a good way of automating the second part, but we could make our lives easier by fixing the first part. The added benefit is we could probably contribute it back upstream as an optional build flag. (The official releases wouldn't use it, so I don't think the case against such a solution would be particularly strong)

### Describe the solution you'd like
An appropriately named build flag that runs a scripted step. That scripted step will run a `sed`-like command that replaces instances of the word "GIMP" with "GNU I.M.P" in the translation files before they are built.

### Describe alternatives you've considered
Running the `sed` line manually. As discussed at the top of this issue, it works to an extent but still requires manual intervention to update translations where we are referring to our own software instead of upstream.

### Additional context
This is something I have briefly discussed with upstream contributors on their IRC channel. I suspect the main reason they don't want to commit resources themselves is that they don't want to deal with the controversy from last summer again.

**Comment by Member1221** [comment]
I'm against this, upstream has expressed no interest in such a feature and it'd just add overhead for us to handle the second step since we'd need to read through everything and figure out where to put "GNU IMP"
Also adding more scripts to the build steps just adds more maintenance overhead for the script and makes the build process even more complex, it's already very complex and honestly I don't think we need to *add* complexity.

**Comment by TrechNex** [comment]
That's a fair comment. We'll stick to a combination of `sed` and manual fixes. 👍
