### ISSUE TITLE
Improve Windows icon visuals at lower resolutions

### ISSUE THREAD

**Issue by ChildishGiant** [glimpse-editor/Glimpse#458]
![image](https://user-images.githubusercontent.com/13716824/91246701-7718d880-e748-11ea-9212-0964b2ad7141.png)

**Comment by BrainBlasted** [comment]
This is intentional. The original icon had poor contrast; However, this new version doesn't seem to have transitioned well into a desktop icon form.

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/91252385-6de23880-e755-11ea-899c-c213432abc82.png)
hmm. I've looked at the files and the white border looks good at those sizes but it certainly needs some editing for small sizes.

**Comment by TrechNex** [comment]
I'm interpreting this as a potential piece of work we can pick up for the next release (0.2.2), as we define this behaviour in the installers I created.

The rationale behind the white border is it helps people that are using dark backgrounds and themes. The pixellation is likely down to the way we exported/compressed the JPG and PNG versions of the same image from an SVG file, so it should be fixable.

You may have noticed at least that the desktop icon looks a lot better than 0.1.2, and the correct icon is now displayed in Add/Remove programs as well as file associations. But we could polish this a lot more.

**Comment by TrechNex** [comment]
I have changed the icon to a borderless one in https://github.com/glimpse-editor/Glimpse/commit/e7d1d61ff3fc8d1dc49fcc38f80ce33e574350c1

We'll verify during beta testing over the next week if this leads to an improvement. (I'm expecting to produce a beta build for 0.2.2 over the weekend)
