### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by chris-short** [glimpse-editor/Glimpse#471]
### Brief Summary
I appreciate your work and wanted to thank you.

### More Details
As a disabled veteran for many years, I've increasingly loathed opening GIMP (let alone the interface and such). This project is what we've needed for a long time.

Thank you.

**Comment by TrechNex** [comment]
Thank you for this. The hostility and scepticism we receive from the wider FLOSS community has had a big impact on us. It takes a lot of time and energy to make this project happen, and @Member1221 & @BrainBlasted have had to talk me out of quitting this project a few times!

Messages like this remind everyone involved that what we're doing is meaningful and that we need to keep doing it. 🙂

**Comment by chris-short** [comment]
Your work has not gone unnoticed. Thank you.

**Comment by Member1221** [comment]
I'll close and lock this issue, thank you for your kind words. :)
(I'll lock it to mainly prevent trolls from posting spam sometime in the future)
