### ISSUE TITLE
  Sustainable governance model

### ISSUE THREAD

**Issue by sk-alexis** [glimpse-editor/Glimpse#478]
Introduction:
I would like to suggest a type of governance economic model to be implemented by glimpse, given that after a conversation with some of the devs, there is a issue of economic sustainability for this project to grow like many other similar projects.

Problem:
Many FOSS or open hardware projects face problems on what relates to economic funding, because the ideals it supports are not compatible with a traditional business model, the other option would be a datamining model, the issue with that is user privacy, because it is not respected bringing another set of problems, and again not compatible with FOSS ideals.

Proposal:
Although this word has been used before as hype in the cryptocurrency camp, so take any articles on it with a grain of salt, which honestly not a big fan of. The original idea has some value, DAOs Decentralized Autonomous Organizations Is the idea to create a token economy so that contributors can be rewarded, and at the same time creating a self sustaining system to support such project with the increase of development. The problem with such economy is that it needs to be setup in such architecture that makes valorisation possible, with the increase of user-base, members, devs, donations, etc, without the need for exterior intervention, in the form of fiat backed development, in other words real world capital effort.

Why is this project a good fit for such system?
Because one of the downfalls of such systems and why it doesn't work for small software projects. Is that a determinate project might have a considerable amount of members, but a lot of them are not participants on such economic system, but in the hardware world is quite the opposite, most members would participate in such economy given that most of them are costumers of such hardware project. creating a high enough market circulation in terms of transactions to increase the value of such token/economy also this doesnt mean the donation scheme cannot be integrated, but at least is not the center of such economic system.

Benefits: If well implemented such software/economic system can make a project self-sustaining, only relying on its own technology/code-base without the need for exterior support, including ability to pay for technical work needed support manufacturing RandD etc.

References: many already developed code-bases could be used to implement such system including but not exclusively BisqDAO, (decentralized cryptocurrencie exchange), Signal dev-reward system, gitcoin, aragon/OpenLaw systems.

Would appreciate any refutations to my suggestion, so such system can be well implemented and refined to work well, also any improvements edits to this post. Cheers
P.S. normally I would boycott github, but given the importance that I feel this topic might have I made such concession, would definitely support a migration to self-hosted systems though see Issue #479  for reference.

**Comment by TrechNex** [comment]
I would suggest taking a read over this FAQ answer: https://glimpse-editor.github.io/about/#how-does-this-project-govern-itself. We also have a section in the FAQs where we describe how the project is currently financed. 

The summary for others reading is that an organization called Open Collective (a 501(c)(6) charity in the USA) takes care of all financial and legal matters on behalf, and that includes the collection of donations. The rest of our governance consists of a group of volunteers sharing infrastructure, and a self-appointed board of three people (called "The Governance Team") act as stewards for the project.

I will take a proper read over your proposal when I next get time. 🙂

**Comment by sk-alexis** [comment]
no wories any feedback refutation is apreciated. Cheers

**Comment by TrechNex** [comment]
Hello, so I have now read over this and done a bit of reading. 🙂 

So first off, I don't have anything specifically against blockchain or blockchain-related solutions. Back in 2016 I actually spent three months being paid by an IT consultancy to research whether there were valid commercial applications for Ethereum that they could subsequently sell to customers.

Theoretically blockchain could be a powerful technology, and I have seen how services like [LBRY](https://lbry.com/) can be a great way for content creators to monetise their content. However, there are also project like [Brave browser](https://en.wikipedia.org/wiki/Brave_(web_browser)) have had a very mixed reception.

My concern as a member of the governance team is mostly related to the "optics". We have had to put a lot of work into rebuilding trust with the community after a rocky launch with our project (see [this FAQ answer](https://glimpse-editor.github.io/about/#are-you-scamming-me) to understand how far we have had to go). I suspect if we try to roll our own cryptocurrency or blockchain, much of that work could be undone.

However, I will keep an open mind and see what the community feedback is. If there is sufficient enthusiasm and support from project contributors and end users, we can spend more time looking into it.

**Comment by sk-alexis** [comment]
@dwkretz could you explain the reasoning behind, of your thinking on this not working,not being viable, or maybe not being a priority right now? Cheers

**Comment by dwkretz** [comment]
I don't find this compelling at all. If I'm being honest it all sounds like vague marketing-speak to my ears

**Comment by TrechNex** [comment]
Marking as Won't fix as it won't be worked on right now, but will leave the issue open for further discussion

**Comment by dwkretz** [comment]
> @dwkretz could you explain the reasoning behind, of your thinking on this not working,not being viable, or maybe not being a priority right now? Cheers

I mean, you're the one making a proposal here with very few details of how it would be implemented or how it could specifically help this project. There's not much to refute

**Comment by sk-alexis** [comment]
@dwkretz I feel the cryptocurrencie nonsense has screwed such important conversations, because when such idea is presented  people instead of really trying to understand the merrit of the idea get stuck in the buzzwords

**Comment by sk-alexis** [comment]
as for your comment Im just reaching out to a couple projects that I think such system would be needed/ have insterest, given that such system will be implemented in another project, and before we do so, Im interested in hearing as much feedback as possible, but if you are not interested in understanding my propusal,it is ok. Hopefully history will prove you wrong. Thank you for your feedback though.

**Comment by TrechNex** [comment]
Locking the issue so OP cannot bypass moderator action with a new Github Account. If there is legitimate interest in developing this proposal, we can unlock this issue again.

**Comment by TrechNex** [comment]
Confirming we have now added an FAQ about this here: https://glimpse-editor.github.io/about/#will-you-adopt-a-cryptocurrency-or-blockchain-reward-system
