### ISSUE TITLE
git repository

### ISSUE THREAD

**Issue by sk-alexis** [glimpse-editor/Glimpse#479]
Did you ever considered using a self-hosted server for the betrusted code-base, that does not really on github services, maybe something based of libregit.org (selfhosted gitea) or gitlab CE, so that this project has full control over modefications modifications and derivative works? Cheers

P.S. please fell free to improve title not my strenght, creating titles that is.

**Comment by TrechNex** [comment]
This is covered on our FAQs page here: https://glimpse-editor.github.io/about/#why-are-you-using-github-instead-of-gitlab

A lot of the suggestions we get do not take into account the resources we have and what the project needs out of them.

Github currently covers the following at zero cost (in time & money):
* Code hosting
* Issue tracking
* Project management
* Wiki hosting
* Donation platform
* Automated builds & CIT
* Build server hosting
* Release mirroring
* Discoverability & End user support (it's the most widely-used VCS in the world)
* External packaging integration (Flathub, Snap Store, AppImage)

I understand the reasoning behind peoples' moral objections to Github. However, the destination has to provide the same level of functionality for the same cost. The time spent doing the migration is also time not being spent on developing the project, so there also tangible & sensible reasons for allocating resources to do that.

We have looked into self-hosting before, and spent hundreds of dollars and hundreds of hours determining we don't actually have the resources to maintain it over the long term.

However, there is a silver-lining if you don't like Github. If you raise an issue to mirror the code to another service, make the case for it and enough people also want it then we can make it happen. 🙂

**Comment by sk-alexis** [comment]
I feel such issue should remain open though if it is you plan in the future to migrate to another platform

**Comment by TrechNex** [comment]
The reason I closed and applied the "Won't fix" label is because there are no plans to migrate any time soon.

The compromise solution is that we can mirror the code on other platforms if people would find that useful. But I would expect that to be raised as a separate ticket. 

I have also made it clear why self-hosted solutions are not going to work for us.

**Comment by sk-alexis** [comment]
@TrechNex Also I only opened this issue so I could reference it on my other feauture request, spoken in the matrix room

**Comment by sk-alexis** [comment]
#478

**Comment by TrechNex** [comment]
Thank you for your input @sk-alexis. I'm locking the issue now as there is the potential for this to become somewhere people start bikeshedding. I will unlock if there is a demonstrated interest in revisiting this policy.

**Comment by sk-alexis** [comment]
sounds good. cheers

**Comment by TrechNex** [comment]
Locking the issue so OP cannot bypass moderator action with a new Github Account. If there is legitimate interest in developing this proposal, we can unlock this issue again.
