### ISSUE TITLE
Copied .desktop file from Snap won't launch

### ISSUE THREAD

**Issue by AmeliaSZK** [glimpse-editor/Glimpse#480]
### Describe the bug
After installing Glimpse from Snap on Ubuntu 18.04, the copied .desktop file will throw an error instead of launching Glimpse. This is unlike Blender, Krita, and Inkscape, for which this method was successful in creating a desktop shortcut.

### To Reproduce
1. In Ubuntu, install Glimpse from snap: `sudo snap install glimpse-editor`
2. With the file explorer, go to `/snap/glimpse-editor/current/meta/gui` 
3. Copy the file `glimpse-editor.desktop`, and paste it on your desktop
4. Right-click on that copied file, and select `Properties`
5. In the Properties window, click on the `Permissions` tab
6. Check the box `Allow executing file as program`
7. Close the Properties window
8. Double-click the `glimpse-editor.desktop` file on your desktop
9. Click on `Trust and Launch` (wording may not be exact, as you only see that warning once)
10. See error message: "There was an error launching the application."

### Expected behavior
Glimpse should launch just like when clicking on its icon in the app menu.

### Screenshots
The error message you see in step 10:
![glimpse-launch-error](https://user-images.githubusercontent.com/49453461/95641225-0ff08280-0a6f-11eb-9f65-60ec2d4f1d23.png)
(Image description: A window where you can see a no-entry icon, followed by the message "There was an error launching the application.", and then a single OK button.)

### Desktop 
 - OS: Ubuntu
 - Version 18.04

### Verbose Logs
"Post logs from running the application with the `--verbose --console-messages` flags"

I ain't posting logs where my username has been plastered all over the place because of file paths in my /home folder.

### Additional context
I wanted to make desktop shortcuts to launch the image editor apps we are using this semester. This method worked for Blender, Krita, and Inkscape, and they were all installed through Snap, because that way I get the icon in the app menu automatically, and I can then easily put them on my taskbar.

I discarded using Flatpack for Glimpse because I don't want to install something that feels as complex as a cross-platform packager manager I never heard of before in my 1 year of using Linux, especially since I expect to upgrade to Ubuntu 20.04 in the next few days.

**Comment by TrechNex** [comment]
If it helps as a short term, we do also have an AppImage. The instructions for download & installation are available here: https://glimpse-editor.github.io/downloads/

As for the desktop shortcut, could you paste the contents of the file you are copying in a comment here? (Feel free to replace info you don't want to share).

My understanding was that the desktop file our snap uses was actually in `/var/lib/snapd/desktop/applications/org.glimpse_editor.Glimpse.desktop`, and that the configuration files specific to your user are in `~/snap/glimpse-editor/current/.config/Glimpse`. (The settings you see in `/var/lib` are system-wide defaults)

**Comment by TrechNex** [comment]
Also cc @hellsworth in case she's aware of a sanctioned way to create desktop shortcuts for snaps through the Ubuntu UI

**Comment by AmeliaSZK** [comment]
Content of the file:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Glimpse Image Editor
Name[ast]=Editor d'imáxenes Glimpse
Name[bg]=Редактор на текст на Glimpse
Name[br]=Embanner testennoù Glimpse
Name[en_CA]=Glimpse Image Editor
Name[eo]=Bildredaktilo Glimpse
Name[tr]=Glimpse Görüntü Düzenleyici
GenericName=Image Editor
GenericName[ar]=محرر صور
GenericName[ast]=Editor d'imaxe
GenericName[be]=Рэдактар відарысаў
GenericName[bg]=Редактор на изображения
GenericName[br]=Embanner skeudennoù
GenericName[bs]=Obrada slika
GenericName[ca]=Editor d'imatges
GenericName[ca@valencia]=Editor d'imatges
GenericName[cs]=Editor obrázků
GenericName[da]=Billedredigering
GenericName[de]=Bildeditor
GenericName[dz]=གཟུགས་བརྙན་ ཞུན་དག་པ།
GenericName[el]=Επεξεργαστής εικόνων
GenericName[en_CA]=Image Editor
GenericName[en_GB]=Image Editor
GenericName[eo]=Bildredaktilo
GenericName[es]=Editor de imagen
GenericName[et]=Pildiredaktor
GenericName[eu]=Irudi-editorea
GenericName[fa]=ویرایشگر تصویر
GenericName[fi]=Kuvankäsittely
GenericName[fr]=Éditeur d’image
GenericName[gd]=Deasaiche dhealbhan
GenericName[gl]=Editor de imaxes
GenericName[gu]=ચિત્ર સંપાદક
GenericName[hr]=Uređivač slika
GenericName[hu]=Képszerkesztő
GenericName[id]=Penyunting Gambar
GenericName[is]=Myndvinnsluforrit
GenericName[it]=Modifica immagine
GenericName[ja]=画像エディター
GenericName[ka]=გამოსახულებების რედაქტორი
GenericName[kk]=Суреттерді өңдеу қолданбасы
GenericName[km]=កម្មវិធី​និពន្ធ​រូបភាព
GenericName[kn]=ಚಿತ್ರ ಸಂಪಾದಕ
GenericName[ko]=이미지 편집기
GenericName[ky]=Сүрөт редактору
GenericName[lt]=Paveikslėlių rengyklė
GenericName[lv]=Attēlu redaktors
GenericName[mk]=Уредник за слики
GenericName[mr]=प्रतिमा संपादक
GenericName[my]=ရုပ်ပုံ တည်းဖြတ်ကိရိယာ
GenericName[nb]=Bildebehandler
GenericName[nds]=Billbewarker
GenericName[ne]=छवि सम्पादक
GenericName[nl]=Editor Afbeeldingen
GenericName[nn]=Bilethandterar
GenericName[oc]=Editor d'imatge
GenericName[pa]=ਚਿੱਤਰ ਐਡੀਟਰ
GenericName[pl]=Edytor obrazów
GenericName[pt]=Editor de imagens
GenericName[pt_BR]=Editor de imagens
GenericName[ro]=Editor de imagini
GenericName[ru]=Редактор изображений
GenericName[sk]=Editor obrázkov
GenericName[sl]=Urejevalnik slik
GenericName[sr]=Обрада фотографија
GenericName[sr@latin]=Obrada slika
GenericName[sv]=Bildredigerare
GenericName[ta]=பிம்ப திருத்தி
GenericName[te]=బొమ్మ కూర్పకము
GenericName[th]=เครื่องมือแก้ไขภาพ
GenericName[tr]=Görüntü Düzenleyici
GenericName[tt]=Sürät Tözätkeç
GenericName[uk]=Редактор зображень
GenericName[vi]=Bộ biên soạn ảnh
GenericName[xh]=UmHleli woMfanekiso
GenericName[zh_CN]=图像编辑器
GenericName[zh_HK]=圖片編輯器
GenericName[zh_TW]=影像編輯器
Comment=Create and edit images
Keywords=graphic;design;illustration;painting;photography;gimp
Keywords[it]=GIMP;grafica;design;illustrazioni;disegno;fotoritocco;
Keywords[nl]=GIMP;grafisch;ontwerp;illustratie;tekenen;
Keywords[pl]=GIMP;grafika;graficzny;design;dizajn;projektowanie;wzornictwo;ilustracja;ilustrowanie;rysunek;rysowanie;rysownictwo;malowanie;malarstwo;obrazy;obrazki;fotografia;zdjęcia;retuszowanie;renderowanie;wtyczki;
Keywords[pt]=GIMP;gráficos;design;desenho;ilustração;pintura;
Keywords[pt_BR]=GIMP;gráficos;design;ilustração;pintura;
Exec=glimpse-editor %U
TryExec=glimpse-0.2
Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/org.glimpse_editor.Glimpse.png
Terminal=false
Categories=Graphics;2DGraphics;RasterGraphics;GTK;
StartupNotify=true
MimeType=image/bmp;image/g3fax;image/gif;image/x-fits;image/x-pcx;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/x-psd;image/x-sgi;image/x-tga;image/x-xbitmap;image/x-xwindowdump;image/x-xcf;image/x-compressed-xcf;image/x-gimp-gbr;image/x-gimp-pat;image/x-gimp-gih;image/tiff;image/jpeg;image/x-psp;application/postscript;image/png;image/x-icon;image/x-xpixmap;image/x-exr;image/x-webp;image/svg+xml;application/pdf;image/x-wmf;image/jp2;image/x-xcursor;
```
A notable detail not visible in plain text is that the text editor highlighted in red the string "Graphics" for `Categories`:
![glimpse-oddity](https://user-images.githubusercontent.com/49453461/95647970-cbcaa580-0aa1-11eb-8113-0694ef5d459a.png)

Also, copy-pasting the file `/var/lib/snapd/desktop/applications/org.glimpse_editor.Glimpse.desktop` actually worked, and better than with my previous method because I didn't need to set the permission and icon.

Content of the functional .desktop file:
```
[Desktop Entry]
X-SnapInstanceName=glimpse-editor
Version=1.0
Type=Application
Name=Glimpse Image Editor
Name[ast]=Editor d'imáxenes Glimpse
Name[bg]=Редактор на текст на Glimpse
Name[br]=Embanner testennoù Glimpse
Name[en_CA]=Glimpse Image Editor
Name[eo]=Bildredaktilo Glimpse
Name[tr]=Glimpse Görüntü Düzenleyici
GenericName=Image Editor
GenericName[ar]=محرر صور
GenericName[ast]=Editor d'imaxe
GenericName[be]=Рэдактар відарысаў
GenericName[bg]=Редактор на изображения
GenericName[br]=Embanner skeudennoù
GenericName[bs]=Obrada slika
GenericName[ca]=Editor d'imatges
GenericName[ca@valencia]=Editor d'imatges
GenericName[cs]=Editor obrázků
GenericName[da]=Billedredigering
GenericName[de]=Bildeditor
GenericName[dz]=གཟུགས་བརྙན་ ཞུན་དག་པ།
GenericName[el]=Επεξεργαστής εικόνων
GenericName[en_CA]=Image Editor
GenericName[en_GB]=Image Editor
GenericName[eo]=Bildredaktilo
GenericName[es]=Editor de imagen
GenericName[et]=Pildiredaktor
GenericName[eu]=Irudi-editorea
GenericName[fa]=ویرایشگر تصویر
GenericName[fi]=Kuvankäsittely
GenericName[fr]=Éditeur d’image
GenericName[gd]=Deasaiche dhealbhan
GenericName[gl]=Editor de imaxes
GenericName[gu]=ચિત્ર સંપાદક
GenericName[hr]=Uređivač slika
GenericName[hu]=Képszerkesztő
GenericName[id]=Penyunting Gambar
GenericName[is]=Myndvinnsluforrit
GenericName[it]=Modifica immagine
GenericName[ja]=画像エディター
GenericName[ka]=გამოსახულებების რედაქტორი
GenericName[kk]=Суреттерді өңдеу қолданбасы
GenericName[km]=កម្មវិធី​និពន្ធ​រូបភាព
GenericName[kn]=ಚಿತ್ರ ಸಂಪಾದಕ
GenericName[ko]=이미지 편집기
GenericName[ky]=Сүрөт редактору
GenericName[lt]=Paveikslėlių rengyklė
GenericName[lv]=Attēlu redaktors
GenericName[mk]=Уредник за слики
GenericName[mr]=प्रतिमा संपादक
GenericName[my]=ရုပ်ပုံ တည်းဖြတ်ကိရိယာ
GenericName[nb]=Bildebehandler
GenericName[nds]=Billbewarker
GenericName[ne]=छवि सम्पादक
GenericName[nl]=Editor Afbeeldingen
GenericName[nn]=Bilethandterar
GenericName[oc]=Editor d'imatge
GenericName[pa]=ਚਿੱਤਰ ਐਡੀਟਰ
GenericName[pl]=Edytor obrazów
GenericName[pt]=Editor de imagens
GenericName[pt_BR]=Editor de imagens
GenericName[ro]=Editor de imagini
GenericName[ru]=Редактор изображений
GenericName[sk]=Editor obrázkov
GenericName[sl]=Urejevalnik slik
GenericName[sr]=Обрада фотографија
GenericName[sr@latin]=Obrada slika
GenericName[sv]=Bildredigerare
GenericName[ta]=பிம்ப திருத்தி
GenericName[te]=బొమ్మ కూర్పకము
GenericName[th]=เครื่องมือแก้ไขภาพ
GenericName[tr]=Görüntü Düzenleyici
GenericName[tt]=Sürät Tözätkeç
GenericName[uk]=Редактор зображень
GenericName[vi]=Bộ biên soạn ảnh
GenericName[xh]=UmHleli woMfanekiso
GenericName[zh_CN]=图像编辑器
GenericName[zh_HK]=圖片編輯器
GenericName[zh_TW]=影像編輯器
Comment=Create and edit images
Keywords=graphic;design;illustration;painting;photography;gimp
Keywords[it]=GIMP;grafica;design;illustrazioni;disegno;fotoritocco;
Keywords[nl]=GIMP;grafisch;ontwerp;illustratie;tekenen;
Keywords[pl]=GIMP;grafika;graficzny;design;dizajn;projektowanie;wzornictwo;ilustracja;ilustrowanie;rysunek;rysowanie;rysownictwo;malowanie;malarstwo;obrazy;obrazki;fotografia;zdjęcia;retuszowanie;renderowanie;wtyczki;
Keywords[pt]=GIMP;gráficos;design;desenho;ilustração;pintura;
Keywords[pt_BR]=GIMP;gráficos;design;ilustração;pintura;
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/glimpse-editor_glimpse-editor.desktop /snap/bin/glimpse-editor %U
Icon=/snap/glimpse-editor/191/usr/share/icons/hicolor/256x256/apps/org.glimpse_editor.Glimpse.png
Terminal=false
Categories=Graphics;2DGraphics;RasterGraphics;GTK;
StartupNotify=true
MimeType=image/bmp;image/g3fax;image/gif;image/x-fits;image/x-pcx;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/x-psd;image/x-sgi;image/x-tga;image/x-xbitmap;image/x-xwindowdump;image/x-xcf;image/x-compressed-xcf;image/x-gimp-gbr;image/x-gimp-pat;image/x-gimp-gih;image/tiff;image/jpeg;image/x-psp;application/postscript;image/png;image/x-icon;image/x-xpixmap;image/x-exr;image/x-webp;image/svg+xml;application/pdf;image/x-wmf;image/jp2;image/x-xcursor;
```
The red highlight of "Graphics" is present just as previously shown. A notable difference seems to be `Exec`, but I didn't do a thorough search, I saw it because the Command in the Properties window was notably different.

Not sure how prevalent this issue will be. I stumbled on it because I first followed the tutorial at https://itsfoss.com/ubuntu-desktop-shortcut/, but then it failed because the snap .desktop file aren't in `/usr/share/applications`. I think I must have seen the snap folder when looking in root, and then searched for `blender.desktop`, and that's how I got the folder path of `/snap/appname/current/meta/gui`?

**Comment by TrechNex** [comment]
I have no idea about the gedit highlighting "Graphics" red, as the GNOME desktop file it relates to passes several very strict linters for the Flatpak, Snap and AppImage packaging processes. 😂 

I am glad we were able to help you find a solution to the problem, and I think this will help others. I don't see any bugs here that need fixing (unless asking blogs to keep their tutorials up to date counts?), so I'll close the issue.

For anyone else who stumbles across this issue, the solution was to copy `/var/lib/snapd/desktop/applications/org.glimpse_editor.Glimpse.desktop` to your `~/Desktop` folder to get a working shortcut to the Snap.
