### ISSUE TITLE
Missing some italian localization

### ISSUE THREAD

**Issue by lucamosca1** [glimpse-editor/Glimpse#485]
Using glimpse 0.2.0 installed as snap on ubuntu 20.04

I notice (small stuff) that some italian localization are missing, not so many ... but are missing.

**Comment by TrechNex** [comment]
Hi @lucamosca1 - have you check the latest release of GNU Image Manipulation Program to see if you have the same problem?

Glimpse Image Editor 0.2.0 is based on 2.10.18 and we inherited their translations. If they have improved in 2.10.20 and 2.10.22 then we may be able to backport it for Glimpse Image Editor 0.2.2.

**Comment by lucamosca1** [comment]
Hi and thanks for response. IMHO just from a very quick view under file dropdown menu 'Export as' and 'close all' are not localized but I don't think has been modified recently. I think that many other strings has the issue.

**Comment by TrechNex** [comment]
Okay. So the way translations work for GNU Image Manipulation Program (and therefore also Glimpse) is that by default all strings used throughout the source code are in US English. 

There's then a translation file that is automatically generated with a reference to the line and code file. IRL humans then make manual changes to those files in a tool call `poedit`. 

If a line has a translation then that is used. If it is not, then the system will either make an educated guess (if it's similar to another translation) or fall back to the US English string.

Your best bet is to take a look in the Help > About > Credits section of the application, as that will provide contact details for the Italian translators. 

If you have spotted gaps then they may be able to fix them in the GNU I.M.P source code which we would then inherit. Alternatively, they may be able to help you get started with fixing translations yourself :)

If you would like to see an example of what translations files typically look like, take a look in the `po` folders in this repository.

**Comment by TrechNex** [comment]
I should point out btw that we do accept translation fixes, but we don't have an agreed pipeline with the upstream maintainers yet on how we contribute them back. Hence why I'm directing you to them.

There are areas we need translating to other languages, so hopefully as our project develops we can set up our own translation tools. 

I think @BrainBlasted has some ideas about using weblate, but that might be more relevant for Glimpse NX.

**Comment by TrechNex** [comment]
Marking this as a question, as this is not something we have the capacity to fix downstream. We currently inherit the translations from the teams providing support to the GNU Image Manipulation Program, then make minor modifications to use "Glimpse" or "GNU I.M.P" instead of "GIMP".
