### ISSUE TITLE
Clipboard size in new file

### ISSUE THREAD

**Issue by fixmycode** [glimpse-editor/Glimpse#486]
### Is your feature request related to a problem? Please describe
Not precisely, but it's a useful feature from another software that has proven very useful.

### Describe the solution you'd like
In the new file dialog, one of the template options could be "Clipboard", allowing you to make a new file of the same dimensions of the image data on the clipboard.

### Describe alternatives you've considered
Other ways to implement this is that the default dimensions of a new file would be the clipboard size if image data is present on the clipboard, like the other software does.

**Comment by TrechNex** [comment]
If it helps, you can use **Edit** > **Paste as** > **New Image** to create a new image containing the image in your clipboard at the correct size automatically. The keyboard shortcut is Ctrl + Shift + V.

**File** > **Create...** > **From Clipboard** also does the same thing.

**Comment by fixmycode** [comment]
Thanks, I didn't know it was already there!
