### ISSUE TITLE
concept layers

### ISSUE THREAD

**Issue by malabo1990** [glimpse-editor/Glimpse#492]
![image](https://user-images.githubusercontent.com/23149831/99532758-15fa4d00-29a5-11eb-88c5-b04c89faf7d5.png)
![image](https://user-images.githubusercontent.com/23149831/99533619-776eeb80-29a6-11eb-871e-c9c74f9e0924.png)

I still haven't seen some concept images of Glimpse NX

Here I propose a panel of layers that can benefit many by visual and also experienced users, it is much easier to use it from a graphic tablet and also for people with low vision that can be very useful.

The layers as the remains (gimp, photoshop. Affinity is fine but I really like it.

In each layer there are two circular buttons:
a is for on and off.

Another to give tootlip for increased list of tool for layers.

**Comment by malabo1990** [comment]
![image](https://user-images.githubusercontent.com/23149831/99535319-0d0b7a80-29a9-11eb-90ef-8d9843bb63a0.png)

**Comment by TrechNex** [comment]
Hi @malabo1990 :)

You may want to raise those ideas here: https://github.com/glimpse-editor/glimpse-nx-design

**Comment by Member1221** [comment]
I'll close this issue as it was posted in the wrong repo, maybe we should make it more clear where to contribute concepts for Glimpse NX?
