### ISSUE TITLE
Windows Installer Silent Mode?

### ISSUE THREAD

**Issue by zag2me** [glimpse-editor/Glimpse#496]
### Brief Summary
Just a quick question, I am trying to roll out Glimpse in our school to 200+ Windows 10 computers. Is there a silent mode for the installer to use?

**Comment by Member1221** [comment]
The installer for glimpse is MSI based you should be able to use the normal silent install options for msis, as can be found here http://www.silentinstall.org/msiexec

**Comment by TrechNex** [comment]
Indeed, I would expect that to work. Microsoft's own docs on this: https://docs.microsoft.com/en-us/windows/win32/msi/command-line-options

If you run into any problems then let me know and I will spend some time this evening (UTC) taking a look at it. If something doesn't default sensibly it's a bug.

If you're familiar with the WiX Toolset, the way we package things for Windows is fully documented here: https://github.com/glimpse-editor/Glimpse/tree/dev-g210/build-aux/windows-msi

**Comment by zag2me** [comment]
Thanks works as expected with the following command for silent install.

`msiexec.exe /i "glimpse-0.2.0-x64.msi" ALLUSERS=1 /qn /norestart`
