### ISSUE TITLE
How to apply Yaru theme to Glimpse flatpak?

### ISSUE THREAD

**Issue by PJSingh5000** [glimpse-editor/Glimpse#508]
### Brief Summary
On Ubuntu 20.04 or 20.10, how can I apply the Yaru theme to Glimpse installed as a flatpak?

Would someone please list the steps/commands I need to execute to make Glimpse flatpak match my system theme in Ubuntu?

### More Details
When I install the snap version, Glimpse uses the default Ubuntu (orange) theme.
When I install the flatpak version, Glimpse uses the default Adwaita (blue) theme.

(I prefer to use flatpak because flatpak apps can be installed in a chroot/container environment, and I customize my ISO in a container before installing. As a result snap is not an option for me.)

**Comment by TrechNex** [comment]
Have you tried installing the Flathub version of the Yaru theme? Flatpaks are sandboxed from the rest of the system, so they default to their own provided Adwaita. My guess is you'd need a command like this:

`flatpak install flathub org.gtk.Gtk3theme.Yaru`

As for the actual theming engine in GNU Image Manipulation Program and Glimpse Image Editor, both use their own custom theme engine on top of GTK2. To change that, you would need to make your own custom theme. You can find those in your config folder.

I am going to keep this issue as an open question as we should take some time to examine the way we package Flatpaks and Snaps to resolve some similar issues related to this.

**Comment by PJSingh5000** [comment]
Indeed, I do have the Gtk flatpak theme installed.

$ flatpak install flathub org.gtk.Gtk3theme.Yaru
Skipping: org.gtk.Gtk3theme.Yaru/x86_64/3.22 is already installed

I know that you can select the theme in Preferences | Interface | Theme.

However, the flatpak version thinks my system theme is Adwaita, while the snap version correctly identifies that I am using Yaru. (See screen shots below).

This is the flatpak version of Glimpse...
![image](https://user-images.githubusercontent.com/19394936/102960723-920a1800-44b0-11eb-9f78-3e2e00ff26ca.png)

This is the snap version of Glimpse...
![image](https://user-images.githubusercontent.com/19394936/102960798-ba921200-44b0-11eb-9566-f88b3ae28850.png)

**Comment by BrainBlasted** [comment]
This isn't a bug we can fix here, unfortunately. Glimpse is a GTK2 app, and the `org.gtk.Gtk3theme` extensions for themes only support GTK3; I don't believe GTK2 can do themes from the sandbox like GTK3 either.
