### ISSUE TITLE
Missing Icons in AppImage

### ISSUE THREAD

**Issue by alfredo-ardito** [glimpse-editor/Glimpse#510]
### Describe the bug
Icons are not displayed.

### To Reproduce
1. Execute Latest AppImage Glimpse 0.2.1
2. Missing Icons all over the App

### Expected behavior
Icons should show up

### Desktop (please complete the following information)
 - OS: Arch Linux kernel 5.10.3-arch1-1

**Comment by jannuary** [comment]
Duplicate of #507?

**Comment by TrechNex** [comment]
I restricted the scope of #507 to only include snaps, so I'm counting this as a separate "bug".

The reason for this behaviour is that the AppImage is only a development build that includes a subset of dependencies and functionality. This means you can't export to JPG or PNG either atm.

In coming weeks I will look at trying to bring the AppImage up to the same level of functionality as the Flatpak & Snap, but will likely need the assistance of @azubieta to do it as I don't fully understand how it all fits together.

**Comment by TrechNex** [comment]
@alfredo-ardito if you need a temporary workaround for now, we do offer a Flatpak that works great. You should also find Glimpse in AUR, although we don't maintain that build ourselves.

**Comment by alfredo-ardito** [comment]
Okay, I'll forward to it

**Comment by azubieta** [comment]
I tracked this issue to a regression bug in appimage-builder, I'm already working on it and should be fixed by the end of the day.

**Comment by alfredo-ardito** [comment]
Well done... great news :)

**Comment by azubieta** [comment]
I fixed the bug mentioned in the issue, but something else showed up. And this seems to be the real cause of the missing icons.

When the appimage is ran using `LD_DEBUG=libs` it spits many undefined symbol errors that look like this:

```
       387:     /tmp/mozilla_alexis0/squashfs-root/usr/lib/x86_64-linux-gnu/gegl-0.4/ppm-save.so: error: symbol lookup error: undefined symbol: g_module_check_init (fatal)
       387:     /tmp/mozilla_alexis0/squashfs-root/usr/lib/x86_64-linux-gnu/gegl-0.4/ppm-save.so: error: symbol lookup error: undefined symbol: g_module_unload (fatal)
       387:     /tmp/mozilla_alexis0/squashfs-root/usr/lib/x86_64-linux-gnu/gegl-0.4/pixbuf-save.so: error: symbol lookup error: undefined symbol: g_module_check_init (fatal)
       387:     /tmp/mozilla_alexis0/squashfs-root/usr/lib/x86_64-linux-gnu/gegl-0.4/pixbuf-save.so: error: symbol lookup error: undefined symbol: g_module_unload (fatal)
       387:     /tmp/mozilla_alexis0/squashfs-root/usr/lib/x86_64-linux-gnu/gegl-0.4/jpg-save.so: error: symbol lookup error: undefined symbol: g_module_check_init (fatal)

```

I'll keep working on it as it affects other gtk based applications.
Tracking link https://github.com/AppImageCrafters/appimage-builder/issues/80

**Comment by azubieta** [comment]
Finally I was able to track down the issue to a miss configuration in the appimage builder defaults. It's already fixed on master.

I'll make a new release this week. In the meantime you can use and test it from here.
https://github.com/azubieta/Glimpse/releases/tag/continuous

**Comment by alfredo-ardito** [comment]
Good work. Tested, works as expected. Thx
