### ISSUE TITLE
Layer-fx

### ISSUE THREAD

**Issue by Aceediq** [glimpse-editor/Glimpse#511]
Yes I know it is a python plugin on gimp but is there going to be any port to glimpse or is there any alternative already on glimpse?

**Comment by TrechNex** [comment]
My understanding is that LayerFX is quite an old plug-in. Most of the functions it provides are now provided by the GNU Image Manipulation Program by default. (Glimpse is currently based on 2.10.18)

If there is missing functionality, G'MIC is a good plugin to investigate as it is still actively maintained.

We provide G'MIC by default on the 64-bit Windows port for Glimpse Image Editor 0.2.0. If you want to use it on Linux, you will need to download the AppImage version of our application and then copy the files to the right configuration folder.

https://github.com/glimpse-editor/Glimpse/wiki/How-to-Install-the-G%27MIC-Plugin

**Comment by Aceediq** [comment]
Yes most of the functions may be provided by Gimp but they are synonymous to hidden treasures, and for one, the Bevel filter on GIMP is a far cry from what it should be, that is, in comparison with what is obtainable in PS...It may be doing what it was programmed to do but there are extra features that are lacking, especially in the area of Text effects/manipulation...

Yes, that is not a healthy comparison since PS is a paid software and Gimp/Glimpse is free but it is said the sky is not the limit...therefore, it wouldn't be bad to have high hopes in Glimpse for something different, right?

Well, well , kudos, you guys are doing a good job, I am elated just to have a usable, comparable free alternative to Gimp with developers trying to tick more and more checkboxes as to what a photo manipulation program should be by today's standards...from a polished UI to slimming down of filrters to really usable ones...MORE GREASE
