### ISSUE TITLE
Automated AppImage not being rebuilt

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#514]
Latest result: https://github.com/glimpse-editor/Glimpse/runs/1841325857?check_suite_focus=true

This has now been broken for over a week, so we may need to prod the AppImage devs again to fix this upstream. cc @azubieta 

<img width="1073" alt="Screenshot 2021-02-05 at 19 27 03" src="https://user-images.githubusercontent.com/45732696/107079809-44d7d080-67e8-11eb-81be-f7407dfb21e3.png">

**Comment by azubieta** [comment]
Sorry, will take care of it.

**Comment by azubieta** [comment]
This is an upstream error, it was fixed already. Please re-trigger the build to test it.
Sorry for the inconveniences

**Comment by TrechNex** [comment]
Can confirm it's now fixed. Thank you @azubieta :)
