### ISSUE TITLE
Over 5500+ slurs present in the repo directory

### ISSUE THREAD

**Issue by k0rnh0li0** [glimpse-editor/Glimpse#524]
Hi gaymers, I'm new to open source and I really want to find an image editor to contribute to.

I wanted to contribute to this project but I found that you have over 5500 files with the offensive slur "gimp" in their name.

```
$ cd Glimpse/
$ find . | grep gimp > grep.txt
$ wc -l grep.txt
5567
```

Is there a reason that the devs chose to name the files this way? I don't feel comfortable working on something like this...

Here is the full list of files with the slur in their name:
[grep.txt](https://github.com/glimpse-editor/Glimpse/files/6066317/grep.txt)

**Comment by LunaTheFoxgirl** [comment]
Obvious troll issue, closing and locking.
