### ISSUE TITLE
The glimpse website seems to be taken over

### ISSUE THREAD

**Issue by ricosuave73** [glimpse-editor/Glimpse#526]
I just visited https://glimpse-editor.org/ and found that there is a site that has a 3d rendering of the periodic elements instead of a site about the glimpse editor.
I also got a certificate warning from Firefox when entering the site. 

### To Reproduce
Visit https://glimpse-editor.org/

### Screenshots
![screenshot_14](https://user-images.githubusercontent.com/2543276/110209265-c6745a00-7e8b-11eb-93e0-fe687a4a9b71.png)

### Additional context
I'm wondering if the project is dead, or if there has been a hack/malicious takeover of the site.

**Comment by LunaTheFoxgirl** [comment]
I am unable to reproduce this issue, there might be specific regions that are highjacked? @BrainBlasted since you have control over the DNS this might be something for you to look in to

**Comment by LunaTheFoxgirl** [comment]
Update others have been able to reproduce this issue, we’ll look in to it ASAP.

**Comment by BrainBlasted** [comment]
Thanks - things should be alright now.

**Comment by LunaTheFoxgirl** [comment]
Do note it might take a few hours for the updated DNS records to propergate to all DNS servers, should be fixed everywhere by tomorrow sometime.
