### ISSUE TITLE
Determine Linux packaging process for Glimpse

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#57]
a) Determine if OpenSUSE Build Service can save us effort packaging rpm/deb/pacman
b) Support packaging as a Flatpak (use upstream as a reference)
c) Determine if the AppImage build is fit for purpose

**Comment by TrechNex** [comment]
Links to #2

**Comment by BrainBlasted** [comment]
Re: AppImage, I'm not sure it's worth the effort. The UX of using appimage is somewhat poor, and the process of building one is distro-dependent. The process of building an appimage seems to rely on making a script or two, rather than writing a flatpak manifest.

**Comment by Member1221** [comment]
Upside of AppImage is that it's known good from my side. So it's a good way to avoid the many bugs still left for the flatpak folks to sort out. As well; the UX is not too bad. It's just an executable that you run (if set to executable) by double clicking. Something a lot of users are used to.

**Comment by TrechNex** [comment]
After discussing on Matrix, my current proposal:

* Flatpak preferred
* AppImage offered as an alternative for those with issues running Flatpaks
* Source archive provided for advanced users & distro package maintainers

**Comment by timClicks** [comment]
I could look into packaging Glimpse as a snap. The snapcraft build service is free and reliable.

**Comment by Member1221** [comment]
@timClicks I don't think we'll be distributing official snaps to start off with.

**Comment by TrechNex** [comment]
@timClicks if you want to have a crack at it, feel free. We're not currently planning to support snaps for 0.1, but if it is ready in the next couple of weeks then it could still make it in.

**Comment by TrechNex** [comment]
Flatpak support at this point is mostly done but waiting on assets and metadata. @Member1221 will be looking into AppImage in due course.

**Comment by TrechNex** [comment]
Linking to #79

**Comment by TrechNex** [comment]
Linking to #108

**Comment by TrechNex** [comment]
Closing as this now duplicates issues related to @bochecha flatpak stuff.
AppImage issue is still being tracked elsewhere. Also #153 is adding support for Snaps.

**Comment by bochecha** [comment]
> Closing as this now duplicates issues related to @bochecha flatpak stuff.

Note that the issues about appdata are not specific to Flatpak, they are just as important for snaps and distro packages at least (no idea about appimage)

**Comment by probonopd** [comment]
AppImage can make use of AppStream metainfo (if you mean that with "appdata").
Just put the file into `<AppDir>/usr/share/metainfo/<myappid>.appdata.xml`.

A basic AppStream metainfo can be made easily using http://output.jsbin.com/qoqukof.

**Comment by bochecha** [comment]
> AppImage can make use of AppStream metainfo

Thank you for confirming.

We do already have an appdata file, it's just incomplete. (see the various issues I opened on the topic for what is left)
