### ISSUE TITLE
Determine Windows packaging process for Glimpse

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#58]
Ideally the build will be automated as described in #2

**Comment by bluikko** [comment]
Is there any possibility to have an MSI installer for Windows?

That would *really* make it easy for enterprises. I understand it might be further down the road since GIMP had only a disappointing .exe installer.

**Comment by Member1221** [comment]
I can look in to packaging an MSI installer. I have experience using WiX to build installers

**Comment by TrechNex** [comment]
I am hoping we can do this in an automated way on our Jenkins build server, as in principle there's no reason why we shouldn't be able to cross-compile & package for Windows on a Linux host. I haven't looked up how to do it yet though!

**Comment by Member1221** [comment]
WiX builds MSI installers via XML defintions, there shouldn't be a problem using wix automated @TrechNex

**Comment by justinhhorner** [comment]
I'd love to see the Windows build be made available via [Chocolatey](http://chocolatey.org)

**Comment by pipboy96** [comment]
@justinhhorner This is a good idea, but not something average user friendly. Making it the only distribution method would not work.

**Comment by justinhhorner** [comment]
@pipboy96 Excellent point! To be clear, I do not want it to be the **only** distribution method, because indeed, that would not work. I want to see if be made available via Chocloately, but not exclusively.

**Comment by Member1221** [comment]
We should not spread ourselves too thin. For our official distribution I personally think an MSI file should be all we should distribute, as we are mainly Linux developers and don't have too much time + resources to put in to maintaining windows packaging.

**Comment by justinhhorner** [comment]
@Member1221 Yes, totally agree. I don't anticipate we will distribute to Chocolatey on day one. Rather, my intention was to say I would like us to provide that method at some point, if and when it makes sense to do so.

**Comment by Member1221** [comment]
@justinhhorner as I said, such an effort will probably be third party. But if a third party script is high quality enough (doesn't contain malware) I think we'd be 100% okay with featuring it on our download page at that point.

**Comment by justinhhorner** [comment]
@Member1221 That sounds great 👍 Thanks for confirming.

**Comment by Member1221** [comment]
I'll close this issue now as it seems we've found a solution that'll work for now.

**Comment by pipboy96** [comment]
@Member1221 Would discussion of updating method on Windows need a separate issue? I feel a good update process is just as important (if not more) as a good install process.

**Comment by Member1221** [comment]
@pipboy96 WiX provides a decent system for updating application files so for WiX it wouldn't be too much of an issue.

We should probably at some point investigate making an update notification widget or something. But that's multiplatform and something we need to consider post-0.1.0

**Comment by pipboy96** [comment]
@Member1221 Is WiX's update process automatic or does it require some actions from the user?

**Comment by Member1221** [comment]
It requires the user to download the new version and install it. It should then overwrite files as neccesary to update the application. It will also detect with an application is newer or the same version as the installer's version and show actions accordingly.

**Comment by pipboy96** [comment]
To clarify, does downloading happen in user's browser/wget/curl/aria2c/whatever download manager or will Glimpse have some kind of downloader?

**Comment by Member1221** [comment]
In the users browser, they'll have to navigate to the project's (upcomming) download page.

**Comment by Member1221** [comment]
We can't drastically improve the installation process until we're in the hard fork stage, since we want to keep the amount of different code per platform low to avoid overhead when issues arise.

Once we're in the hard fork stage, we'll probably create an in-app widget notifying the user that a new version is available that they can click to download the new version.

**Comment by pipboy96** [comment]
Thanks for clarifying!
