### ISSUE TITLE
Determine Mac packaging process for Glimpse

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#59]
Will ideally be automated as described in #2

**Comment by Member1221** [comment]
For mac, to start off with the easiest package format we could use is homebrew.

**Comment by dxf** [comment]
.pkg would also be a good release format to allow for large institutions to deploy without major fuss iirc, although asking someone on r/macsysadmin may be a good idea.

**Comment by Member1221** [comment]
Don't you need to sign the app via apple before you can really deploy apps via dmg files?

**Comment by pipboy96** [comment]
For updating on macOS [Sparkle](https://github.com/sparkle-project/Sparkle) seems to be the standard. There are also numerous projects for packaging the app into a nice-looking DMG file.

**Comment by TrechNex** [comment]
Currently planning to get this working on TravisCI.

Mac build process for upstream found here, but is for CircleCI and their Mac server is costly: https://gitlab.gnome.org/Infrastructure/gimp-macos-build

**Comment by TrechNex** [comment]
Unfortunately after a few weeks I've run into a number of road blocks trying to get this working. It either needs someone more Mac savvy than I to puzzle out the build/packaging process, or we need to ask upstream.

Resources from my efforts:
https://github.com/TrechNex/gimp-macos-build
https://github.com/TrechNex/gimp-osx
https://github.com/TrechNex/glimpse-mac-build (furthest I got with this)
https://wiki.gimp.org/wiki/Hacking:Building

**Comment by TrechNex** [comment]
If there is no advance on this then we may need to initially release on Windows and Linux, then delay the Mac port until this is resolved.

**Comment by TrechNex** [comment]
Cleared milestone & close issue as we're dropping support for MacOS at the current time. We will re-open it when we determine how to build the code and establish how the result will be maintained over the longer term.
