### ISSUE TITLE
Update "gimp" to "glimpse" in the top-level code

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#6]
This would include the core code built from the folders outside the "lib" components and all the make files that replace them.

Given how large this task is, this may have to be turned into a tracking issue.

**Comment by TreacherousNexus** [comment]
It's possible this will be kicked to the next release, as the first one may not be a hard fork.

**Comment by TrechNex** [comment]
Marking as "wontfix" because it is not necessary for the 2.10.12 release, and we're working on a UI rewrite anyway
