### ISSUE TITLE
Investigate porting textures from Krita

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#63]
Suggested by @lorendias. "I strongly suggest removing New Image Templates suchas Toilet Paper, Legacy Textures, and adding Textures where the License permits from Krita -- they have some amazing defaults. "

**Comment by TrechNex** [comment]
Moving this into the 1.0.0 milestone. We definitely need to replace the low res tiles that are already there, and if we can figure out how to add new ones we should consider adding some from Krita (after checking license)

**Comment by TrechNex** [comment]
I've brought this forward as a 0.2.x candidate as I intend to investigate if the `data/` directory is something we can adjust to include more modern textures.

I don't know if the Krita ones will be compatible or not. If necessary, we can look into how we create our own high resolution replacements.

**Comment by chaomodus** [comment]
Textures in Krita appear to have the same use as patterns in Glimpse (as an aside, the ux for using patterns in Krita is surprisingly confusing, while in Glimpse, is suprisingly good).

The textures in Krita are just b/w png files. We could manually convert them to pattern files (.pat), or figure out a way to automate it, or even better figure out how to allow glimpse to load non .pat files as patterns. 

I did a little digging in the plumbing but it's pretty intricate. It does appear that .pats are loaded with a normal format loader, so it may be really easy.

**Comment by TrechNex** [comment]
Closing as a duplicate of #288
