### ISSUE TITLE
Update "libgimp*" components to "libglimpse*"

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#7]
The scope of this covers the components libraries such as libgimp, libgimbase, etc.

Again, this may have to be turned into a tracking issue if the size of the task turns out to be large.

**Comment by TreacherousNexus** [comment]
It's possible this will be kicked to the next release, as the first one may not be a hard fork.

**Comment by TrechNex** [comment]
We should determine if this is actually needed. If not, then we can close this as "wontfix" because it's not necessary for the functioning of releases based on 2.10.12 and we're working on a UI rewrite anyway.

**Comment by TrechNex** [comment]
Brought in provisionally as a 0.2.x candidate as packagers would appreciate this change. We did make changes to libgimp, and some Linux distros and variants of BSD package that separately (thus causing conflicts)

**Comment by igalic** [comment]
i'd love to help whoever is attempting this task, it's gonna be at least as much fun as renaming the binaries

how hard is this gonna make it to merge upstream changes?

**Comment by TrechNex** [comment]
If we're being brutally honest @igalic it's probably going to be me 😅 

With 0.2.0 I'm going to be rebasing the code to 2.10.14, so that will give an indication of how well our changes are preserved between upstream microversions. This is why I think that's probably the best release to target with this change if we're going to do it.

The sticking points I think are going to be a) how does it affect the main code? b) how does it impact plugins? & c) just how much refactoring is this going to require?

**Comment by TrechNex** [comment]
Set to be in the 0.1.6 release scheduled for June 2020.

Refactoring will start after 0.1.4 is release (scheduled for some time in April 2020)

**Comment by TrechNex** [comment]
Let's get this done in the 0.1.4 release! Packagers will love it, and we can finally get that monkey of our project's back.

cc @igalic as she expressed an interest in helping with this.

**Comment by TrechNex** [comment]
Added note to document `--disable-python` flag for maintainers now that Python 2 is end of life and they're starting remove it from their repositories.

**Comment by TrechNex** [comment]
For whoever takes over the code after leaving the project, I recommend you don't actually do this because it breaks binary compatibility with third-party plugins. That means you would have to patch and repackage every third-party plugin to make them Glimpse-compatible, and it's doubtful that plugin developers will want to upstream those changes.

Standardising on the `glimpse-editor` command and updating the man pages is a good plan though, as it ensures that the packaged version of the application follows the appropriate conventions in Linux/UNIX systems.
