### ISSUE TITLE
Update authors.xml with Glimpse contributions

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#8]
I'm currently working on the assumption it makes sense to just append our contributors to it, but it may be we need to re-jig things a little to separate downstream contributions from upstream.

This should be done shortly before release.

**Comment by Member1221** [comment]
My current solution in my PR (https://github.com/TreacherousNexus/Wilber/pull/20) is to have the original GNU Image Manipulation Program contributors listed in a seperate file (ORIGINAL_AUTHORS) then re-rigging the authors.xml file to focus on Glimpse/Wilber contributors.

**Comment by Member1221** [comment]
This has been implemented with my latest PR (+ your additions)

**Comment by TrechNex** [comment]
Linking to #49
