### ISSUE TITLE
What to do with the DOAP file?

### ISSUE THREAD

**Issue by bochecha** [glimpse-editor/Glimpse#82]
> DOAP (Description of a Project) is an RDF Schema and XML vocabulary to describe software projects, in particular free and open source software.

https://en.wikipedia.org/wiki/DOAP

---

It doesn't seem to be commonly used outside of GNOME, where every single project, library and app, has a `${name}.doap` file.

One thing that uses it is GNOME Builder. There, Glimpse shows as « GIMP », because that's how the project is named in the DOAP file.

I see a couple of possibilities:

* modify the DOAP file to have it contain correct information, and rename it to `glimpse.doap`;
* remove it entirely, considering how rare it is outside of GNOME.

Both options are fine.

In particular, when it can't find a `*.doap` file in a project, GNOME Builder will fallback on some other mechanisms to find the project name. (unverified, but most likely the `*.desktop` file, `configure.ac` or something like that) With #79 and #81 merged and the DOAP removed, Builder shows the project named as « Glimpse ».

The status quo is wrong and confusing though. Which option do people prefer?

**Comment by BrainBlasted** [comment]
I think it's fine to keep it - but modified. This way we don't need to recreate it if we ever move to gitlab.gnome.org.
