### ISSUE TITLE
Fix or replace libmypaint and mypaint-brushes

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#83]
We need to investigate how the latest versions of these packages differ from the versions traditionally bundled with upstream and determine if they are fit for purpose.

If they are not we should replace these packages with our own replacements, taking inspiration from tools like Krita.

**Comment by BrainBlasted** [comment]
I'm personally wary about making large functionality changes in the 0.x series. I think this would be something to explore when we gain our own project identity via the 1.x series.

**Comment by nevillepark** [comment]
IIRC Mypaint and GIMP now use different and incompatible library versions which means installing one automatically uninstalls the other. GIMP can be installed as a Snap program, but the sandboxing messes up Mypaint's handy "edit layer in external editor" feature.

It would be great if they could be made compatible again; I'm not sure whether it would have to be on Glimpse's end or Mypaint's.

**Comment by TrechNex** [comment]
The workaround atm is to build with mypaint 1.3.0 code and ignore 2.0.0. It is possible upstream will fix this in time for hard fork from v3

**Comment by TrechNex** [comment]
In addendum to my previous comment, we should review what is new about mypaint 2.0 before jettisoning it in UI rewrite

**Comment by TrechNex** [comment]
Bringing this in to 0.2.x candidate as it seems the files related to this are in `data/brushes`. We could potentially replace them with higher resolution versions much earlier as a result (assuming they're compatible)

**Comment by TrechNex** [comment]
Provisionally moved into 0.1.4 as I think with help from @chaomodus we could probably update some of the textures and brushes.

**Comment by TrechNex** [comment]
Closing as a duplicate of #288
