### ISSUE TITLE
Update doc files we're keeping with Glimpse-specific instructions

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#9]
There are a number of files that explain how to build, hack or contribute to the GNU Image Manipulation Program. It makes sense that we would update these to reflect this project instead.

**Comment by Member1221** [comment]
This should also be a part of my latest PR, is there anything missing?

**Comment by TrechNex** [comment]
Both of us are making changes for this issue, so I figured it makes sense to have a single issue to track them in. 

The alternative is we have to have a separate issue for each minor change to the UI/help pages/menus/about window/credits window

**Comment by TrechNex** [comment]
There is still a fair amount of old cruft in the repository that still needs tweaking and changing imho. We can track multiple PRs for this issue if needed.

**Comment by TrechNex** [comment]
We need to open a new issue for docs required for 1.0
